using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Asegura la tabla seguimiento_diario_aves_engorde_panama.
    /// La entidad está mapeada y SeguimientoAvesEngordePanamaService la usa, pero la tabla
    /// se creó en prod por SQL crudo y no existía en entornos locales (el código manda).
    /// Idempotente: no toca nada si la tabla ya existe.
    /// </summary>
    public partial class EnsureSeguimientoDiarioAvesEngordePanamaTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.seguimiento_diario_aves_engorde_panama (
                    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    lote_ave_engorde_id         INTEGER NOT NULL,
                    fecha                       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    mortalidad_hembras          INTEGER NULL,
                    mortalidad_machos           INTEGER NULL,
                    sel_h                       INTEGER NULL,
                    sel_m                       INTEGER NULL,
                    error_sexaje_hembras        INTEGER NULL,
                    error_sexaje_machos         INTEGER NULL,
                    consumo_kg_hembras          NUMERIC(12,3) NULL,
                    consumo_kg_machos           NUMERIC(12,3) NULL,
                    tipo_alimento               VARCHAR(100) NULL,
                    observaciones               TEXT NULL,
                    ciclo                       VARCHAR(50) NULL,
                    peso_prom_hembras           DOUBLE PRECISION NULL,
                    peso_prom_machos            DOUBLE PRECISION NULL,
                    uniformidad_hembras         DOUBLE PRECISION NULL,
                    uniformidad_machos          DOUBLE PRECISION NULL,
                    cv_hembras                  DOUBLE PRECISION NULL,
                    cv_machos                   DOUBLE PRECISION NULL,
                    consumo_agua_diario         DOUBLE PRECISION NULL,
                    consumo_agua_ph             DOUBLE PRECISION NULL,
                    consumo_agua_orp            DOUBLE PRECISION NULL,
                    consumo_agua_temperatura    DOUBLE PRECISION NULL,
                    metadata                    JSONB NULL,
                    items_adicionales           JSONB NULL,
                    kcal_al_h                   DOUBLE PRECISION NULL,
                    prot_al_h                   DOUBLE PRECISION NULL,
                    kcal_ave_h                  DOUBLE PRECISION NULL,
                    prot_ave_h                  DOUBLE PRECISION NULL,
                    created_by_user_id          VARCHAR(64) NULL,
                    created_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    updated_at                  TIMESTAMP WITHOUT TIME ZONE NULL,
                    saldo_alimento_kg           NUMERIC(18,3) NULL,
                    historico_consumo_alimento  JSONB NULL,
                    qq_mixtas                   NUMERIC(12,3) NULL,
                    qq_hembras                  NUMERIC(12,3) NULL,
                    qq_machos                   NUMERIC(12,3) NULL
                );

                CREATE INDEX IF NOT EXISTS ix_seguimiento_diario_aves_engorde_panama_lote
                    ON public.seguimiento_diario_aves_engorde_panama (lote_ave_engorde_id);
                CREATE INDEX IF NOT EXISTS ix_seguimiento_diario_aves_engorde_panama_fecha
                    ON public.seguimiento_diario_aves_engorde_panama (fecha);

                -- FK a lote_ave_engorde (Restrict), solo si no existe aún.
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'fk_seguimiento_diario_aves_engorde_panama_lote'
                    ) THEN
                        ALTER TABLE public.seguimiento_diario_aves_engorde_panama
                            ADD CONSTRAINT fk_seguimiento_diario_aves_engorde_panama_lote
                            FOREIGN KEY (lote_ave_engorde_id)
                            REFERENCES public.lote_ave_engorde (lote_ave_engorde_id)
                            ON DELETE RESTRICT;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intencionalmente vacío: no se elimina una tabla con datos de producción.
        }
    }
}
