using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCohortesEngordeYUbicacionOrigen : Migration
    {
        /// <summary>
        /// IDEMPOTENTE (regla del repo): el deploy aplica las migraciones al arrancar y esta puede
        /// encontrarse una BD donde la tabla o las columnas ya existan (p. ej. un reintento tras un
        /// deploy fallido). Se escribe en SQL crudo con IF NOT EXISTS en vez de con los helpers de EF,
        /// que fallarían con 42701/42P07.
        /// </summary>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── Postura: ubicación del lote ORIGEN congelada en la cohorte ──────────────────
            migrationBuilder.Sql(@"
                ALTER TABLE public.lote_aves_cohortes
                    ADD COLUMN IF NOT EXISTS granja_origen_id integer,
                    ADD COLUMN IF NOT EXISTS nucleo_origen_id character varying(50),
                    ADD COLUMN IF NOT EXISTS galpon_origen_id character varying(50);
            ");

            // ── Engorde: cohortes de aves recibidas (no existían) ───────────────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.lote_engorde_aves_cohortes (
                    id                          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    lote_ave_engorde_id         integer NOT NULL,
                    lote_ave_engorde_origen_id  integer,
                    movimiento_pollo_engorde_id integer,
                    granja_origen_id            integer,
                    nucleo_origen_id            character varying(50),
                    galpon_origen_id            character varying(50),
                    fecha_ingreso               date NOT NULL,
                    fecha_encaset_cohorte       date NOT NULL,
                    cantidad_hembras            integer NOT NULL DEFAULT 0,
                    cantidad_machos             integer NOT NULL DEFAULT 0,
                    cantidad_mixtas             integer NOT NULL DEFAULT 0,
                    observaciones               character varying(300),
                    company_id                  integer NOT NULL,
                    created_by_user_id          integer NOT NULL,
                    created_at                  timestamp with time zone NOT NULL,
                    updated_by_user_id          integer,
                    updated_at                  timestamp with time zone,
                    deleted_at                  timestamp with time zone,
                    CONSTRAINT pk_lote_engorde_aves_cohortes PRIMARY KEY (id),
                    CONSTRAINT fk_lote_engorde_aves_cohortes_lote
                        FOREIGN KEY (lote_ave_engorde_id)
                        REFERENCES public.lote_ave_engorde (lote_ave_engorde_id)
                        ON DELETE RESTRICT
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ix_lote_engorde_aves_cohortes_lote
                    ON public.lote_engorde_aves_cohortes (lote_ave_engorde_id);
                CREATE INDEX IF NOT EXISTS ix_lote_engorde_aves_cohortes_company
                    ON public.lote_engorde_aves_cohortes (company_id);
                CREATE INDEX IF NOT EXISTS ix_lote_engorde_aves_cohortes_movimiento
                    ON public.lote_engorde_aves_cohortes (movimiento_pollo_engorde_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.lote_engorde_aves_cohortes;");
            migrationBuilder.Sql(@"
                ALTER TABLE public.lote_aves_cohortes
                    DROP COLUMN IF EXISTS granja_origen_id,
                    DROP COLUMN IF EXISTS nucleo_origen_id,
                    DROP COLUMN IF EXISTS galpon_origen_id;
            ");
        }
    }
}
