using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTablaGuiaGeneticaSantaReyes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotente (CLAUDE.md Sec.BD): CREATE TABLE/INDEX IF NOT EXISTS en vez de lo generado,
            // para poder re-correr la migracion sin romper si el objeto ya esta en la BD.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.guia_genetica_santa_reyes (
                    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    raza                  character varying(80)  NOT NULL,
                    anio_guia             character varying(10)  NOT NULL,
                    edad                  integer                NOT NULL,
                    prod_porcentaje       numeric(6,2)            NULL,
                    retiro_ac_h           numeric(6,2)            NULL,
                    gr_ave_dia_h          numeric(7,2)            NULL,
                    codigo_guia_genetica  character varying(150)  NULL,
                    company_id            integer                NOT NULL,
                    created_by_user_id    integer                NOT NULL,
                    created_at            timestamp with time zone NOT NULL,
                    updated_by_user_id    integer                 NULL,
                    updated_at            timestamp with time zone NULL,
                    deleted_at            timestamp with time zone NULL
                );");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS ix_guia_genetica_santa_reyes_raza_anio " +
                "ON public.guia_genetica_santa_reyes (company_id, raza, anio_guia);");

            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS ux_guia_genetica_santa_reyes_codigo " +
                "ON public.guia_genetica_santa_reyes (company_id, codigo_guia_genetica) " +
                "WHERE deleted_at IS NULL AND codigo_guia_genetica IS NOT NULL;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.guia_genetica_santa_reyes;");
        }
    }
}
