using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Esquema de la <b>doble validación</b> de los seguimientos diarios: el flag por empresa, la
    /// marca de validación por registro y las dos tablas de separación (reserva) de alimento y aves.
    /// </summary>
    /// <remarks>
    /// <b>No cambia el comportamiento de nadie.</b> El flag nace en <c>false</c> para todas las
    /// empresas, así que hasta que alguien lo encienda el descuento sigue ocurriendo al guardar,
    /// exactamente como hoy.
    ///
    /// <para>
    /// <b>Backfill:</b> todo lo ya registrado se marca <c>validado = true</c>. Esos registros YA
    /// descontaron su alimento y sus aves; dejarlos en <c>false</c> los pintaría a todos en rojo como
    /// «en retraso» y, peor, una validación posterior volvería a descontar lo que ya se descontó. Es
    /// el mismo criterio que usó reproductora con <c>confirmado</c> en julio.
    /// </para>
    ///
    /// <para>
    /// <b>Reproductora no recibe columna:</b> reusa su <c>confirmado</c>, que es lo que lee
    /// <c>fn_cruce_reproductora_a_engorde</c> para decidir qué días cruzan a pollo engorde. Una
    /// columna nueva dejaría al cruce mirando un flag que ya nadie escribe.
    /// </para>
    ///
    /// <para>
    /// <b>Una reserva no es un movimiento:</b> estas tablas no tocan <c>inventario_gestion_stock</c>
    /// ni escriben en <c>inventario_gestion_movimiento</c>, así que tampoco llegan al espejo
    /// <c>lote_registro_historico_unificado</c>. Solo comprometen cantidad; el disponible pasa a ser
    /// <c>stock − reservas activas</c>.
    /// </para>
    ///
    /// <para>
    /// Todo el DDL es <b>idempotente</b> (<c>IF NOT EXISTS</c>), como exige la guía del repositorio:
    /// las migraciones se aplican solas al arrancar la app en cada deploy y una a medias no puede
    /// dejar el historial inconsistente.
    /// </para>
    /// </remarks>
    public partial class AddValidacionYSeparacionSeguimientosDiarios : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
-- ═══ 1) Flag por empresa ═══════════════════════════════════════════════════════════════════
ALTER TABLE public.companies
    ADD COLUMN IF NOT EXISTS requiere_validacion_seguimiento_diario boolean NOT NULL DEFAULT false;

-- ═══ 2) Marca de validación por registro ═══════════════════════════════════════════════════
ALTER TABLE public.seguimiento_diario_levante
    ADD COLUMN IF NOT EXISTS validado     boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS validado_at  timestamptz NULL,
    ADD COLUMN IF NOT EXISTS validado_por varchar(64) NULL;

ALTER TABLE public.seguimiento_diario_produccion
    ADD COLUMN IF NOT EXISTS validado     boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS validado_at  timestamptz NULL,
    ADD COLUMN IF NOT EXISTS validado_por varchar(64) NULL;

ALTER TABLE public.seguimiento_diario_aves_engorde
    ADD COLUMN IF NOT EXISTS validado     boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS validado_at  timestamptz NULL,
    ADD COLUMN IF NOT EXISTS validado_por varchar(64) NULL;

-- La tabla de Ecuador no existe en todos los entornos (la base local, restaurada de un dump, tiene
-- seguimiento_diario_aves_engorde_panama y no esta). Se toca solo si esta: un seed que asume una
-- tabla y no la encuentra tumba el arranque de la app, y esta migracion corre en cada deploy.
DO $ecu$
BEGIN
    IF to_regclass('public.seguimiento_diario_aves_engorde_ecuador') IS NOT NULL THEN
        ALTER TABLE public.seguimiento_diario_aves_engorde_ecuador
            ADD COLUMN IF NOT EXISTS validado     boolean NOT NULL DEFAULT false,
            ADD COLUMN IF NOT EXISTS validado_at  timestamptz NULL,
            ADD COLUMN IF NOT EXISTS validado_por varchar(64) NULL;

        UPDATE public.seguimiento_diario_aves_engorde_ecuador SET validado = true WHERE validado = false;
    ELSE
        RAISE NOTICE 'seguimiento_diario_aves_engorde_ecuador no existe en este entorno; se omite.';
    END IF;
END
$ecu$;

-- ═══ 3) Backfill: lo que ya existe YA descontó ═════════════════════════════════════════════
-- Sin esto, un registro viejo quedaria pendiente y validarlo descontaria por segunda vez.
UPDATE public.seguimiento_diario_levante      SET validado = true WHERE validado = false;
UPDATE public.seguimiento_diario_produccion   SET validado = true WHERE validado = false;
UPDATE public.seguimiento_diario_aves_engorde SET validado = true WHERE validado = false;

-- ═══ 4) Separación de alimento ═════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.seguimiento_reserva_alimento (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id                 integer NOT NULL,
    pais_id                    integer NOT NULL,
    farm_id                    integer NOT NULL,
    nucleo_id                  varchar(50) NULL,
    galpon_id                  varchar(50) NULL,
    silo_id                    integer NULL,
    item_inventario_ecuador_id integer NOT NULL,
    es_item_inventario         boolean NOT NULL DEFAULT true,
    origen_modulo              varchar(24) NOT NULL,
    origen_seguimiento_id      bigint NOT NULL,
    lote_ref                   varchar(64) NULL,
    fecha_seguimiento          date NOT NULL,
    cantidad_kg                numeric(18,3) NOT NULL,
    unit                       varchar(20) NOT NULL DEFAULT 'kg',
    estado                     varchar(12) NOT NULL DEFAULT 'ACTIVA',
    created_at                 timestamptz NOT NULL DEFAULT now(),
    created_by_user_id         varchar(64) NULL,
    aplicada_at                timestamptz NULL,
    liberada_at                timestamptz NULL,
    CONSTRAINT pk_seguimiento_reserva_alimento PRIMARY KEY (id),
    CONSTRAINT fk_seguimiento_reserva_alimento_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_seguimiento_reserva_alimento_farms_farm_id
        FOREIGN KEY (farm_id) REFERENCES public.farms (id) ON DELETE RESTRICT,
    CONSTRAINT fk_seguimiento_reserva_alimento_item_inventario_ecuador_item_i
        FOREIGN KEY (item_inventario_ecuador_id) REFERENCES public.item_inventario_ecuador (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_alimento_company_id
    ON public.seguimiento_reserva_alimento (company_id);
CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_alimento_item_inventario_ecuador_id
    ON public.seguimiento_reserva_alimento (item_inventario_ecuador_id);
CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_alimento_origen
    ON public.seguimiento_reserva_alimento (origen_modulo, origen_seguimiento_id);
CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_alimento_ubicacion_item_estado
    ON public.seguimiento_reserva_alimento (farm_id, item_inventario_ecuador_id, nucleo_id, galpon_id, silo_id, estado);

-- Idempotencia REAL de la separación: un mismo registro no puede tener dos reservas ACTIVAS del
-- mismo ítem en el mismo silo. Sin esto, un reintento del guardado duplicaría lo comprometido.
CREATE UNIQUE INDEX IF NOT EXISTS ux_seguimiento_reserva_alimento_activa
    ON public.seguimiento_reserva_alimento (origen_modulo, origen_seguimiento_id, item_inventario_ecuador_id, COALESCE(silo_id, 0))
    WHERE estado = 'ACTIVA';

-- ═══ 5) Separación de aves ═════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.seguimiento_reserva_aves (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id            integer NOT NULL,
    origen_modulo         varchar(24) NOT NULL,
    origen_seguimiento_id bigint NOT NULL,
    lote_ref_int          integer NOT NULL,
    lote_ref              varchar(64) NULL,
    fecha_seguimiento     date NOT NULL,
    hembras               integer NOT NULL DEFAULT 0,
    machos                integer NOT NULL DEFAULT 0,
    mixtas                integer NOT NULL DEFAULT 0,
    estado                varchar(12) NOT NULL DEFAULT 'ACTIVA',
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by_user_id    varchar(64) NULL,
    aplicada_at           timestamptz NULL,
    liberada_at           timestamptz NULL,
    CONSTRAINT pk_seguimiento_reserva_aves PRIMARY KEY (id),
    CONSTRAINT fk_seguimiento_reserva_aves_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_aves_company_id
    ON public.seguimiento_reserva_aves (company_id);
CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_aves_lote_estado
    ON public.seguimiento_reserva_aves (origen_modulo, lote_ref_int, estado);
CREATE INDEX IF NOT EXISTS ix_seguimiento_reserva_aves_origen
    ON public.seguimiento_reserva_aves (origen_modulo, origen_seguimiento_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_seguimiento_reserva_aves_activa
    ON public.seguimiento_reserva_aves (origen_modulo, origen_seguimiento_id)
    WHERE estado = 'ACTIVA';
");
        }

        /// <inheritdoc />
        /// <remarks>
        /// Revierte el esquema entero. El backfill no se deshace porque las columnas desaparecen con
        /// él: no queda rastro que revertir.
        /// </remarks>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.seguimiento_reserva_alimento;
DROP TABLE IF EXISTS public.seguimiento_reserva_aves;

ALTER TABLE public.seguimiento_diario_levante
    DROP COLUMN IF EXISTS validado,
    DROP COLUMN IF EXISTS validado_at,
    DROP COLUMN IF EXISTS validado_por;

ALTER TABLE public.seguimiento_diario_produccion
    DROP COLUMN IF EXISTS validado,
    DROP COLUMN IF EXISTS validado_at,
    DROP COLUMN IF EXISTS validado_por;

ALTER TABLE public.seguimiento_diario_aves_engorde
    DROP COLUMN IF EXISTS validado,
    DROP COLUMN IF EXISTS validado_at,
    DROP COLUMN IF EXISTS validado_por;

DO $ecu$
BEGIN
    IF to_regclass('public.seguimiento_diario_aves_engorde_ecuador') IS NOT NULL THEN
        ALTER TABLE public.seguimiento_diario_aves_engorde_ecuador
            DROP COLUMN IF EXISTS validado,
            DROP COLUMN IF EXISTS validado_at,
            DROP COLUMN IF EXISTS validado_por;
    END IF;
END
$ecu$;

ALTER TABLE public.companies
    DROP COLUMN IF EXISTS requiere_validacion_seguimiento_diario;
");
        }
    }
}
