using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Lote base global de pollo engorde: catálogo lote_base_engorde (por empresa) +
    /// amarre OPCIONAL lote_ave_engorde.lote_base_engorde_id. Todo idempotente
    /// (IF NOT EXISTS) para poder re-ejecutar sin romper el historial.
    /// </summary>
    public partial class AddLoteBaseEngorde : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
-- 1) Catálogo de lotes base (agrupador global por empresa)
CREATE TABLE IF NOT EXISTS public.lote_base_engorde (
    id                  integer GENERATED BY DEFAULT AS IDENTITY,
    nombre              character varying(80)  NOT NULL,
    descripcion         character varying(300) NULL,
    company_id          integer NOT NULL,
    created_by_user_id  integer NOT NULL DEFAULT 0,
    created_at          timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
    updated_by_user_id  integer NULL,
    updated_at          timestamp with time zone NULL,
    deleted_at          timestamp with time zone NULL,
    CONSTRAINT pk_lote_base_engorde PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_lote_base_engorde_company
    ON public.lote_base_engorde (company_id);

-- Unicidad por empresa (case-insensitive) entre vivos
CREATE UNIQUE INDEX IF NOT EXISTS ux_lote_base_engorde_company_nombre
    ON public.lote_base_engorde (company_id, LOWER(nombre))
    WHERE deleted_at IS NULL;

-- 2) Amarre opcional en lote_ave_engorde
ALTER TABLE public.lote_ave_engorde
    ADD COLUMN IF NOT EXISTS lote_base_engorde_id integer NULL;

CREATE INDEX IF NOT EXISTS ix_lote_ave_engorde_lote_base
    ON public.lote_ave_engorde (lote_base_engorde_id);

-- 3) FK (sin IF NOT EXISTS nativo → DO block)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_lote_ave_engorde_lote_base_engorde_lote_base_engorde_id'
          AND conrelid = 'public.lote_ave_engorde'::regclass
    ) THEN
        ALTER TABLE public.lote_ave_engorde
            ADD CONSTRAINT fk_lote_ave_engorde_lote_base_engorde_lote_base_engorde_id
            FOREIGN KEY (lote_base_engorde_id)
            REFERENCES public.lote_base_engorde (id)
            ON DELETE RESTRICT;
    END IF;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_lote_ave_engorde_lote_base_engorde_lote_base_engorde_id",
                schema: "public",
                table: "lote_ave_engorde");

            migrationBuilder.DropTable(
                name: "lote_base_engorde",
                schema: "public");

            migrationBuilder.DropIndex(
                name: "ix_lote_ave_engorde_lote_base",
                schema: "public",
                table: "lote_ave_engorde");

            migrationBuilder.DropColumn(
                name: "lote_base_engorde_id",
                schema: "public",
                table: "lote_ave_engorde");
        }
    }
}
