// Partial de la migracion AddAlimentoEntregaCicloEngorde: SOLO la constante SQL, que es
// backend/sql/create_alimento_entrega_ciclo_engorde.sql tal cual. Vive separada para que el archivo
// principal se pueda leer, y byte a byte para que el .sql no quede muerto.

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    public partial class AddAlimentoEntregaCicloEngorde
    {
        /// <summary>
        /// Tabla del hecho + sus 4 indices + el indice parcial del historico + los 2 triggers de
        /// anulacion en cascada. Todo con IF NOT EXISTS / CREATE OR REPLACE / DROP TRIGGER IF EXISTS,
        /// asi que se puede aplicar dos veces sin efecto.
        /// </summary>
        private const string DdlAlimentoEntregaCicloEngorde = """
-- =============================================================================
-- alimento_entrega_ciclo_engorde — la ATRIBUCION del alimento marcado «para el proximo ciclo»,
-- persistida como HECHO.
--
-- Espejo del DDL que aplica la migracion EF 20260818130139_AddAlimentoEntregaCicloEngorde. Los dos
-- tienen que decir lo mismo: un .sql cambiado sin migracion queda MUERTO (aprendizaje del repo).
-- Plan: fase_de_desarrollo/v16_engorde_atribucion_persistida_plan.md (FASE B, §3.2)
--
-- POR QUE EXISTE ESTA TABLA
-- Hasta la v16 la atribucion era un veredicto que fn_seguimiento_diario_engorde RECALCULABA en cada
-- lectura sobre estado mutable. La liquidacion congela UN SOLO extremo del handoff, asi que al
-- re-leer el otro extremo cambiaba de opinion y el handoff se partia:
--   * liquidar el CEDENTE escondia 3.000 kg reales (apertura del destino 3.000 -> 0, cuadre -3.000);
--   * liquidar el DESTINO los duplicaba (Sigma galpon 8.640 -> 11.640) con descuadre_kg = 0,00 en los
--     dos estados, o sea con el detector CIEGO.
-- Fue el NO-GO del gate. Ahora la atribucion se decide y se ESCRIBE una vez, y la fn la LEE: congelar
-- un extremo deja de poder cambiar lo que ve el otro porque no queda nada que recalcular.
--
-- LA INTENCION Y EL HECHO SON COSAS DISTINTAS
-- `lote_registro_historico_unificado.para_proximo_ciclo` (y su espejo en
-- `inventario_gestion_movimiento`) guardan lo que la PERSONA pidio. Esta tabla guarda lo que el
-- sistema RESOLVIO a partir de ese pedido. Por eso no se agregan columnas al historico: son ciclos de
-- vida distintos, y el historico lo llena un trigger AFTER INSERT que no propaga ningun UPDATE.
--
-- UNA FILA LEIDA POR DOS LOTES
-- El cedente la ve como salida en `fecha_entrega`; el destino, como credito de apertura. Por los
-- MISMOS `kg_entregados`. Ninguno de los dos puede dejar de honrarla unilateralmente ⇒ los dos
-- bloqueantes del NO-GO son inconstruibles.
-- TIPOS: varchar(N) con las MISMAS longitudes que la configuracion EF, no TEXT. El plan
-- esbozaba TEXT, pero toda la vecindad (lote_registro_historico_unificado: nucleo_id y
-- galpon_id varchar(64), origen_tabla varchar(80)) usa varchar, y si el DDL y el modelo EF
-- discrepan el proximo `migrations add` genera un AlterColumn fantasma para «arreglarlo».
-- Igual con la identidad: GENERATED BY DEFAULT AS IDENTITY, que es lo que emite EF, no BIGSERIAL.
-- =============================================================================

CREATE TABLE IF NOT EXISTS alimento_entrega_ciclo_engorde (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INT           NOT NULL,
    farm_id            INT           NOT NULL,
    -- Cadena vacia, NO null: la fn compara la ubicacion con COALESCE(TRIM(...), ''), asi que un NULL
    -- aca haria que el JOIN por ubicacion no encuentre nunca la entrega.
    nucleo_id          VARCHAR(64)   NOT NULL DEFAULT '',
    galpon_id          VARCHAR(64)   NOT NULL,

    -- El movimiento del que nace. (origen_tabla, origen_id) es la clave REAL: la misma que usa
    -- uq_lote_hist_origen. Colgarse de ella una sola vez evita repetir el fallback fragil por
    -- granja+nucleo+galpon+item+cantidad, que con dos ingresos identicos puede marcar el otro.
    origen_tabla       VARCHAR(80)   NOT NULL,
    origen_id          BIGINT        NOT NULL,
    hist_id            BIGINT        NULL,
    fecha_movimiento   DATE          NOT NULL,
    kg_movimiento      NUMERIC(18,3) NOT NULL,
    numero_documento   VARCHAR(200)  NULL,

    -- El HECHO.
    lote_cedente_id    INT           NULL,
    lote_destino_id    INT           NULL,
    fecha_entrega      DATE          NULL,
    kg_entregados      NUMERIC(18,3) NOT NULL DEFAULT 0,
    kg_no_diferible    NUMERIC(18,3) NOT NULL DEFAULT 0,   -- residuo = anomalia R2, se SENALA
    estado             VARCHAR(20)   NOT NULL,             -- PENDIENTE|VIGENTE|INERTE|ANULADA
    motivo             VARCHAR(400)  NULL,                 -- texto legible para la bandeja
    sellada            BOOLEAN       NOT NULL DEFAULT FALSE,

    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by_user_id VARCHAR(100)  NULL,
    anulada_at         TIMESTAMPTZ   NULL,
    anulada_por_user_id VARCHAR(100) NULL,
    anulada_motivo     VARCHAR(400)  NULL,

    -- Solo una entrega VIGENTE mueve kg, y para moverlos necesita los dos extremos y la fecha. Sin
    -- este CHECK, un bug del escritor podria dejar kg_entregados > 0 con lote_destino_id NULL: la fn
    -- los restaria del cedente y nadie los recibiria.
    CONSTRAINT ck_entrega_kg_solo_vigente
        CHECK (kg_entregados = 0 OR (estado = 'VIGENTE' AND lote_cedente_id IS NOT NULL
               AND lote_destino_id IS NOT NULL AND fecha_entrega IS NOT NULL)),
    CONSTRAINT ck_entrega_kg_no_negativos CHECK (kg_entregados >= 0 AND kg_no_diferible >= 0),
    CONSTRAINT ck_entrega_estado
        CHECK (estado IN ('PENDIENTE','VIGENTE','INERTE','ANULADA'))
);

-- Un movimiento tiene UNA entrega viva. Las anuladas quedan (el historico se anula, nunca se borra),
-- asi que se excluyen del unico para que puedan acumularse sin chocar con la nueva.
CREATE UNIQUE INDEX IF NOT EXISTS uq_entrega_ciclo_origen
    ON alimento_entrega_ciclo_engorde (origen_tabla, origen_id) WHERE estado <> 'ANULADA';

CREATE INDEX IF NOT EXISTS ix_entrega_ciclo_ubicacion
    ON alimento_entrega_ciclo_engorde (farm_id, nucleo_id, galpon_id, fecha_movimiento);

-- Parciales: la fn entra por aca una vez por lote y solo le interesan las VIGENTE. Con 0 entregas el
-- costo es ~0, que es el estado de produccion hoy.
CREATE INDEX IF NOT EXISTS ix_entrega_ciclo_cedente
    ON alimento_entrega_ciclo_engorde (lote_cedente_id) WHERE estado = 'VIGENTE';
CREATE INDEX IF NOT EXISTS ix_entrega_ciclo_destino
    ON alimento_entrega_ciclo_engorde (lote_destino_id) WHERE estado = 'VIGENTE';

-- El indice parcial que el intento anterior dijo haber creado y nunca existio: sin el, buscar los
-- movimientos marcados de un galpon es un seq scan sobre todo el historico unificado.
CREATE INDEX IF NOT EXISTS ix_lote_hist_para_proximo_ciclo
    ON lote_registro_historico_unificado (farm_id, nucleo_id, galpon_id, fecha_operacion)
    WHERE para_proximo_ciclo;

-- =============================================================================
-- ANULACION EN CASCADA — el hecho se ANULA, nunca se abandona.
--
-- `lote_registro_historico_unificado` la llena un trigger AFTER INSERT: ningun UPDATE ni DELETE del
-- origen se propaga solo. Esta tabla es una tabla espejo mas, asi que replica el patron que ya
-- garantizan trg_inventario_gestion_movimiento_lote_hist_del y _cancel. Sin esto, anular un ingreso
-- dejaria una entrega VIGENTE apuntando a un movimiento que ya no existe, y la fn seguiria restando
-- esos kg del cedente para siempre.
--
-- ⚠️ Una entrega SELLADA igual se anula: no se puede impedir desde un trigger sin romper el
-- inventario. Pero queda con `anulada_motivo` explicito y el caso aparece como anomalia en
-- GET /liquidados-con-alimento. Es R2: senalar, no esconder.
-- =============================================================================

CREATE OR REPLACE FUNCTION fn_anular_entrega_ciclo_por_movimiento()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_mov_id BIGINT;
    v_motivo TEXT;
BEGIN
    -- Mismo molde que trg_lote_hist_anular_desde_inventario_gestion, que sirve a los dos TG_OP.
    v_mov_id := CASE TG_OP WHEN 'DELETE' THEN OLD.id ELSE NEW.id END;
    v_motivo := CASE TG_OP WHEN 'DELETE' THEN 'movimiento origen eliminado'
                                         ELSE 'movimiento origen anulado' END;

    UPDATE alimento_entrega_ciclo_engorde e
       SET estado         = 'ANULADA',
           kg_entregados  = 0,
           anulada_at     = now(),
           anulada_motivo = CASE WHEN e.sellada
                                 THEN v_motivo || ' (la entrega estaba SELLADA: un extremo ya tiene '
                                                || 'liquidacion congelada, revisar la anomalia)'
                                 ELSE v_motivo END
     WHERE e.origen_tabla = 'inventario_gestion_movimiento'
       AND e.origen_id    = v_mov_id
       AND e.estado      <> 'ANULADA';

    RETURN CASE TG_OP WHEN 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS trg_entrega_ciclo_engorde_mov_del ON inventario_gestion_movimiento;
CREATE TRIGGER trg_entrega_ciclo_engorde_mov_del
    AFTER DELETE ON inventario_gestion_movimiento
    FOR EACH ROW EXECUTE FUNCTION fn_anular_entrega_ciclo_por_movimiento();

-- ⚠️ La condicion es la MISMA, literal, que la de trg_inventario_gestion_movimiento_lote_hist_cancel
-- (verificada en pg_get_triggerdef): el unico movement_type que hoy significa «anulado» es
-- 'TrasladoInterGranjaRechazado'. NO se generaliza a un ILIKE '%anulad%': seria inventar una
-- semantica que el resto del sistema no tiene. Si algun dia aparece otra forma de anular un
-- movimiento, los DOS triggers tienen que crecer juntos, o el historico se anulara y la entrega no.
DROP TRIGGER IF EXISTS trg_entrega_ciclo_engorde_mov_cancel ON inventario_gestion_movimiento;
CREATE TRIGGER trg_entrega_ciclo_engorde_mov_cancel
    AFTER UPDATE OF movement_type ON inventario_gestion_movimiento
    FOR EACH ROW
    WHEN (NEW.movement_type = 'TrasladoInterGranjaRechazado')
    EXECUTE FUNCTION fn_anular_entrega_ciclo_por_movimiento();
""";
    }
}
