using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddLiquidacionLoteEngordePanama : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tabla idempotente (CLAUDE.md): protege contra re-runs / aplicación parcial previa.
            migrationBuilder.Sql(TABLE_SQL, suppressTransaction: true);

            // Función SQL que arma el reporte "RESULTADOS DE LIQUIDACIÓN" (Panamá) a partir de
            // los 6 insumos de liquidacion_lote_engorde_panama + agregados del seguimiento Panamá.
            migrationBuilder.Sql(FN_SQL, suppressTransaction: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS public.fn_reporte_indicadores_panama(INT);", suppressTransaction: true);

            migrationBuilder.DropTable(
                name: "liquidacion_lote_engorde_panama",
                schema: "public");
        }

        // Fórmulas verificadas contra el JSON de la plataforma origen + screenshot:
        //   peso_promedio        = produccion_kilo_pie / aves_beneficiada
        //   mortalidad_porc      = total_aves_muertas    / aves_encasetadas * 100
        //   seleccion_porc       = total_aves_seleccion  / aves_encasetadas * 100
        //   supervivencia        = 100 - (mortalidad_porc + seleccion_porc)
        //   consumo_kg_total     = SUM(consumo_dia_kg) de fn_seguimiento_diario_engorde(p_lote_id)
        //   consumo_alimento_total (qq, display) = consumo_kg_total / 45.36   (1 quintal = 100 lb)
        //   consumo_ave          = consumo_kg_total / aves_beneficiada
        //   conversion           = consumo_kg_total / produccion_kilo_pie
        //   eef                  = produccion_kilo_pie * supervivencia / (dias_engorde * conversion) * 100
        //   eef_dos              = peso_promedio       * supervivencia / (dias_engorde * conversion) * 100
        //   eficiencia_americana = (peso_promedio * 2.2046) / dias_engorde
        //   productividad        = eficiencia_americana / conversion
        //   aves_metros_cua      = aves_beneficiada   / metros_cuadrados
        //   kilos_metros_cua     = produccion_kilo_pie / metros_cuadrados
        //   faltante_sobra       = aves_final_granja  - aves_beneficiada
        private const string TABLE_SQL = @"
CREATE TABLE IF NOT EXISTS public.liquidacion_lote_engorde_panama (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_ave_engorde_id     integer NOT NULL,
    metros_cuadrados        numeric(14,2) NOT NULL,
    aves_final_granja       integer NOT NULL,
    aves_beneficiada        integer NOT NULL,
    produccion_kilo_pie     numeric(16,2) NOT NULL,
    dias_engorde            integer NOT NULL,
    dias_en_granja          integer NOT NULL,
    registrado_por_user_id  character varying(64) NULL,
    created_at              timestamp with time zone NOT NULL,
    updated_at              timestamp with time zone NULL,
    CONSTRAINT fk_liquidacion_lote_engorde_panama_lote
        FOREIGN KEY (lote_ave_engorde_id)
        REFERENCES public.lote_ave_engorde (lote_ave_engorde_id)
        ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_liquidacion_lote_engorde_panama_lote
    ON public.liquidacion_lote_engorde_panama (lote_ave_engorde_id);
";

        private const string FN_SQL = @"
CREATE OR REPLACE FUNCTION public.fn_reporte_indicadores_panama(p_lote_id INT)
RETURNS TABLE (
    id                       INT,
    id_usuario_registro      TEXT,
    id_lote                  INT,
    metros_cuadrados         NUMERIC,
    aves_final_granja        NUMERIC,
    produccion_kilo_pie      NUMERIC,
    dias_engorde             INT,
    dias_en_granja           INT,
    aves_beneficiada         INT,
    peso_promedio            NUMERIC,
    mortalidad_porc          NUMERIC,
    seleccion_porc           NUMERIC,
    porc_mortalidad_total    NUMERIC,
    supervivencia            NUMERIC,
    consumo_ave              NUMERIC,
    conversion               NUMERIC,
    eficiencia_americana     NUMERIC,
    eef                      NUMERIC,
    eef_dos                  NUMERIC,
    aves_metros_cua          NUMERIC,
    kilos_metros_cua         NUMERIC,
    productividad            NUMERIC,
    faltante_sobra           NUMERIC,
    consumo_alimento_total   NUMERIC,
    total_aves_seleccion     NUMERIC,
    total_aves_muertas       NUMERIC,
    aves_encasetadas         INT
)
LANGUAGE sql
STABLE
AS $$
WITH liq AS (
    SELECT lq.*
    FROM public.liquidacion_lote_engorde_panama lq
    WHERE lq.lote_ave_engorde_id = p_lote_id
),
lote AS (
    SELECT COALESCE(l.aves_encasetadas, 0) AS aves_encasetadas
    FROM public.lote_ave_engorde l
    WHERE l.lote_ave_engorde_id = p_lote_id AND l.deleted_at IS NULL
),
-- El seguimiento diario de pollo engorde NO tiene tabla propia para el reporte:
-- se arma con la función fn_seguimiento_diario_engorde (misma fuente que usa el módulo
-- de Seguimiento). Devuelve el consumo en KG (consumo_dia_kg).
seg AS (
    SELECT
        COALESCE(SUM(COALESCE(f.consumo_dia_kg,0)),0)::NUMERIC                                       AS consumo_kg_total,
        COALESCE(SUM(COALESCE(f.sel_h,0)+COALESCE(f.sel_m,0)),0)::NUMERIC                            AS total_aves_seleccion,
        COALESCE(SUM(COALESCE(f.mortalidad_hembras,0)+COALESCE(f.mortalidad_machos,0)),0)::NUMERIC   AS total_aves_muertas
    FROM fn_seguimiento_diario_engorde(p_lote_id) f
),
base AS (
    SELECT
        liq.id,
        liq.registrado_por_user_id,
        liq.lote_ave_engorde_id,
        liq.metros_cuadrados,
        liq.aves_final_granja::NUMERIC AS aves_final_granja,
        liq.produccion_kilo_pie,
        liq.dias_engorde,
        liq.dias_en_granja,
        liq.aves_beneficiada,
        COALESCE(lote.aves_encasetadas, 0) AS aves_encasetadas,
        -- consumo_alimento_total se muestra en quintales (qq) como en la plataforma origen
        (seg.consumo_kg_total / 45.36) AS consumo_alimento_total,
        seg.total_aves_seleccion,
        seg.total_aves_muertas,
        seg.consumo_kg_total
    FROM liq, lote, seg
),
d AS (
    SELECT b.*,
        CASE WHEN b.aves_beneficiada > 0    THEN b.produccion_kilo_pie / b.aves_beneficiada ELSE 0 END AS peso_promedio,
        CASE WHEN b.aves_encasetadas > 0    THEN b.total_aves_muertas    / b.aves_encasetadas * 100 ELSE 0 END AS mortalidad_porc,
        CASE WHEN b.aves_encasetadas > 0    THEN b.total_aves_seleccion  / b.aves_encasetadas * 100 ELSE 0 END AS seleccion_porc,
        CASE WHEN b.produccion_kilo_pie > 0 THEN b.consumo_kg_total / b.produccion_kilo_pie ELSE 0 END AS conversion,
        CASE WHEN b.aves_beneficiada > 0    THEN b.consumo_kg_total / b.aves_beneficiada ELSE 0 END AS consumo_ave
    FROM base b
),
d2 AS (
    SELECT d.*,
        (d.mortalidad_porc + d.seleccion_porc)        AS porc_mortalidad_total,
        (100 - (d.mortalidad_porc + d.seleccion_porc)) AS supervivencia
    FROM d
)
SELECT
    d2.id,
    d2.registrado_por_user_id::TEXT,
    d2.lote_ave_engorde_id,
    d2.metros_cuadrados,
    d2.aves_final_granja,
    d2.produccion_kilo_pie,
    d2.dias_engorde,
    d2.dias_en_granja,
    d2.aves_beneficiada,
    d2.peso_promedio,
    d2.mortalidad_porc,
    d2.seleccion_porc,
    d2.porc_mortalidad_total,
    d2.supervivencia,
    d2.consumo_ave,
    d2.conversion,
    CASE WHEN d2.dias_engorde > 0 THEN (d2.peso_promedio * 2.2046) / d2.dias_engorde ELSE 0 END,
    CASE WHEN d2.dias_engorde > 0 AND d2.conversion > 0
         THEN d2.produccion_kilo_pie * d2.supervivencia / (d2.dias_engorde * d2.conversion) * 100 ELSE 0 END,
    CASE WHEN d2.dias_engorde > 0 AND d2.conversion > 0
         THEN d2.peso_promedio * d2.supervivencia / (d2.dias_engorde * d2.conversion) * 100 ELSE 0 END,
    CASE WHEN d2.metros_cuadrados > 0 THEN d2.aves_beneficiada / d2.metros_cuadrados ELSE 0 END,
    CASE WHEN d2.metros_cuadrados > 0 THEN d2.produccion_kilo_pie / d2.metros_cuadrados ELSE 0 END,
    CASE WHEN d2.dias_engorde > 0 AND d2.conversion > 0
         THEN ((d2.peso_promedio * 2.2046) / d2.dias_engorde) / d2.conversion ELSE 0 END,
    (d2.aves_final_granja - d2.aves_beneficiada),
    d2.consumo_alimento_total,
    d2.total_aves_seleccion,
    d2.total_aves_muertas,
    d2.aves_encasetadas
FROM d2;
$$;
";
    }
}
