using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddMigracionMasiva : Migration
    {
        // NOTA: sólo crea la tabla `migracion_masiva` (auditoría del módulo de Migraciones Masivas).
        // El scaffolder de EF también propuso renombrar 3 FKs de inventario (drift cosmético del
        // refactor "inventario rename neutro": la BD conserva a propósito los nombres de constraint
        // viejos). Esas operaciones se OMITEN aquí para no meter DDL ajeno/arriesgado en prod; el
        // snapshot ya refleja los nombres nuevos, así que no reaparecen en migraciones futuras.
        // Idempotente (CREATE TABLE/INDEX IF NOT EXISTS) según CLAUDE.md.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS migracion_masiva (
                    id                 integer GENERATED BY DEFAULT AS IDENTITY,
                    tipo               character varying(40)  NOT NULL,
                    nombre_archivo     character varying(400) NOT NULL,
                    filas_totales      integer NOT NULL DEFAULT 0,
                    filas_procesadas   integer NOT NULL DEFAULT 0,
                    filas_error        integer NOT NULL DEFAULT 0,
                    estado             character varying(20)  NOT NULL,
                    errores            jsonb NULL,
                    fecha_proceso      timestamp with time zone NOT NULL,
                    company_id         integer NOT NULL,
                    created_by_user_id integer NOT NULL,
                    created_at         timestamp with time zone NOT NULL,
                    updated_by_user_id integer NULL,
                    updated_at         timestamp with time zone NULL,
                    deleted_at         timestamp with time zone NULL,
                    CONSTRAINT pk_migracion_masiva PRIMARY KEY (id)
                );
                CREATE INDEX IF NOT EXISTS ix_migracion_masiva_company_id ON migracion_masiva (company_id);
                CREATE INDEX IF NOT EXISTS ix_migracion_masiva_tipo       ON migracion_masiva (tipo);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS migracion_masiva;");
        }
    }
}
