using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Congelar la liquidación de un lote de pollo engorde (plan congelar_liquidacion_lote_engorde).
    ///
    /// La tabla diaria de engorde NO es una foto: fn_seguimiento_diario_engorde recalcula en cada
    /// request, y el 28-jul-2026 un cambio de fórmula (v9→v12) movió corridas CERRADAS hacía meses.
    /// Esta migración, en orden y en un solo archivo:
    ///   1. Cabecera  liquidacion_lote_engorde_congelada  (mapeada en EF; única VIGENTE por lote).
    ///   2. Detalle   liquidacion_lote_engorde_congelada_fila — las 47 columnas del RETURNS TABLE,
    ///      SOLO SQL: no se mapea en EF porque su única lectura es dentro de la fn v13 (mapearla
    ///      sería mantener el mismo esquema en un tercer lugar).
    ///   3. fn_congelar_liquidacion_engorde / fn_anular_… / fn_recongelar_…
    ///   4. Trigger trg_lote_ave_engorde_anula_congelada — la BD garantiza el invariante
    ///      «Cerrado ⟺ copia vigente» ante cualquier UPDATE crudo, no la disciplina de C#.
    ///   5. fn_seguimiento_diario_engorde v13: SIGUE en LANGUAGE sql (conserva el inlining en los
    ///      LATERAL de los reportes — una variante plpgsql lo perdía y multiplicaba ×2.8 el Reporte
    ///      de Costos, medido). La conmutación es UNION ALL con quals excluyentes y One-Time
    ///      Filter; el cuerpo v12 queda VERBATIM (los 5 consumidores —tabla diaria, Reporte de
    ///      Costos, Informe Semanal Panamá, Cuadre y saldo persistido— quedan congelados con este
    ///      único cambio).
    ///   6. Backfill: congela los lotes ya 'Cerrado' (verificado local: EC 20 / PA 0; los 3
    ///      reabiertos NO) con los valores actuales post-v12. El resumen tipado queda NULL
    ///      (origen='backfill') — el modal cae al cálculo vivo hasta la primera reliquidación.
    ///
    /// Idempotente: correrla dos veces no duplica nada (IF NOT EXISTS + NOT EXISTS del backfill).
    /// Down(): restaura la fn v12 (LANGUAGE sql) y elimina trigger, fns y tablas.
    /// Las constantes FnSeguimientoDiarioEngordeV13/V12 viven en el partial `.Fn.cs`.
    /// </summary>
    public partial class AddLiquidacionLoteEngordeCongelada : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── 1. Cabecera (espejo idempotente del modelo EF) ────────────────────────────────
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS liquidacion_lote_engorde_congelada (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lote_ave_engorde_id     INTEGER NOT NULL,
    company_id              INTEGER NOT NULL,
    granja_id               INTEGER NOT NULL,
    liquidado_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    liquidado_por_user_id   TEXT NOT NULL,
    congelada_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    origen                  CHARACTER VARYING(30) NOT NULL,
    fn_version              CHARACTER VARYING(30) NOT NULL,
    filas                   INTEGER NOT NULL,
    checksum                CHARACTER VARYING(64) NOT NULL,
    lote_nombre             TEXT NOT NULL,
    estado_operativo_lote   CHARACTER VARYING(20) NOT NULL,
    hembras_inicio          INTEGER NULL,
    machos_inicio           INTEGER NULL,
    mixtas_inicio           INTEGER NULL,
    total_aves_inicio       INTEGER NULL,
    ventas_total_hembras    INTEGER NULL,
    ventas_total_machos     INTEGER NULL,
    ventas_total_mixtas     INTEGER NULL,
    aves_vivas_actuales     INTEGER NULL,
    movimientos_venta_count INTEGER NULL,
    saldo_alimento_kg       NUMERIC(18,3) NULL,
    merma_unidades          INTEGER NULL,
    merma_kilos             NUMERIC(18,3) NULL,
    metadata                JSONB NULL,
    anulada_at              TIMESTAMP WITH TIME ZONE NULL,
    anulada_por_user_id     TEXT NULL,
    anulada_motivo          TEXT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_user_id      TEXT NULL,
    CONSTRAINT pk_liquidacion_lote_engorde_congelada PRIMARY KEY (id),
    CONSTRAINT fk_liquidacion_lote_engorde_congelada_lote_ave_engorde_lote_av
        FOREIGN KEY (lote_ave_engorde_id)
        REFERENCES public.lote_ave_engorde (lote_ave_engorde_id) ON DELETE CASCADE
);

-- ⭐ El invariante: a lo sumo UNA copia VIGENTE por lote (dos cierres concurrentes / retry del
-- front ⇒ el segundo INSERT falla y su transacción revierte entera).
CREATE UNIQUE INDEX IF NOT EXISTS ux_liquidacion_lote_engorde_congelada_vigente
    ON liquidacion_lote_engorde_congelada (lote_ave_engorde_id)
    WHERE anulada_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_liquidacion_lote_engorde_congelada_lote
    ON liquidacion_lote_engorde_congelada (lote_ave_engorde_id, congelada_at DESC);

CREATE INDEX IF NOT EXISTS ix_liquidacion_lote_engorde_congelada_company
    ON liquidacion_lote_engorde_congelada (company_id, congelada_at DESC);
""");

            // ── 2. Detalle: las 47 columnas del RETURNS TABLE, MISMOS nombres y MISMOS tipos ──
            //     Regla dura: DOUBLE PRECISION se guarda como DOUBLE PRECISION — convertirlo a
            //     numeric "para que quede prolijo" cambiaría el redondeo y la copia dejaría de
            //     ser la foto (refactor ≠ cambio de comportamiento).
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS liquidacion_lote_engorde_congelada_fila (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    liquidacion_id   BIGINT NOT NULL,
    orden            INTEGER NOT NULL,
    -- las 47 columnas de fn_seguimiento_diario_engorde, verbatim
    seg_id                      BIGINT,
    fecha                       DATE,
    edad_dia                    INT,
    semana                      SMALLINT,
    mortalidad_hembras          INT,
    mortalidad_machos           INT,
    sel_h                       INT,
    sel_m                       INT,
    error_sexaje_hembras        INT,
    error_sexaje_machos         INT,
    total_mort_sel_dia          INT,
    perdidas_totales_dia        INT,
    consumo_kg_hembras          DOUBLE PRECISION,
    consumo_kg_machos           DOUBLE PRECISION,
    consumo_dia_kg              DOUBLE PRECISION,
    acum_consumo_kg             DOUBLE PRECISION,
    saldo_aves                  INT,
    pct_perdidas_dia            DOUBLE PRECISION,
    saldo_alimento_kg           DOUBLE PRECISION,
    ingreso_alimento_kg         DOUBLE PRECISION,
    traslado_entrada_kg         DOUBLE PRECISION,
    traslado_salida_kg          DOUBLE PRECISION,
    consumo_bodega_kg           DOUBLE PRECISION,
    documento                   TEXT,
    despacho_hembras            INT,
    despacho_machos             INT,
    despacho_mixtas             INT,
    despacho_peso_neto          DOUBLE PRECISION,
    despacho_peso_tara          DOUBLE PRECISION,
    despacho_promedio_peso_ave  DOUBLE PRECISION,
    tipo_alimento               TEXT,
    peso_prom_hembras           DOUBLE PRECISION,
    peso_prom_machos            DOUBLE PRECISION,
    uniformidad_hembras         DOUBLE PRECISION,
    uniformidad_machos          DOUBLE PRECISION,
    cv_hembras                  DOUBLE PRECISION,
    cv_machos                   DOUBLE PRECISION,
    consumo_agua_diario         DOUBLE PRECISION,
    consumo_agua_ph             DOUBLE PRECISION,
    consumo_agua_orp            DOUBLE PRECISION,
    consumo_agua_temperatura    DOUBLE PRECISION,
    observaciones               TEXT,
    ciclo                       TEXT,
    metadata                    JSONB,
    items_adicionales           JSONB,
    historico_consumo_alimento  JSONB,
    created_by_user_id          TEXT,
    CONSTRAINT pk_liquidacion_lote_engorde_congelada_fila PRIMARY KEY (id),
    CONSTRAINT fk_liq_engorde_congelada_fila_cabecera
        FOREIGN KEY (liquidacion_id)
        REFERENCES liquidacion_lote_engorde_congelada (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_liquidacion_lote_engorde_congelada_fila_liq
    ON liquidacion_lote_engorde_congelada_fila (liquidacion_id, orden);
""");

            // ── 3a. fn_congelar_liquidacion_engorde ───────────────────────────────────────────
            //  TODO el copiado en UN statement (CTEs modificantes = mismo snapshot): la cabecera
            //  recién insertada no le tapa la lectura al detalle — fn_seguimiento_diario_engorde
            //  todavía calcula EN VIVO dentro de este statement.
            migrationBuilder.Sql("""
CREATE OR REPLACE FUNCTION fn_congelar_liquidacion_engorde(p_lote_id INT, p_user TEXT, p_origen TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
AS $fn$
DECLARE
    v_id BIGINT;
BEGIN
    IF EXISTS (SELECT 1 FROM liquidacion_lote_engorde_congelada c
                WHERE c.lote_ave_engorde_id = p_lote_id AND c.anulada_at IS NULL) THEN
        RAISE EXCEPTION 'El lote % ya tiene una liquidación congelada vigente.', p_lote_id;
    END IF;

    WITH lote AS (
        SELECT l.lote_ave_engorde_id,
               l.company_id,
               l.granja_id,
               COALESCE(l.liquidado_at, now())                                        AS liquidado_at,
               COALESCE(NULLIF(TRIM(l.liquidado_por_user_id), ''), p_user)            AS liquidado_por,
               COALESCE(NULLIF(TRIM(l.lote_nombre), ''), l.lote_ave_engorde_id::text) AS lote_nombre,
               COALESCE(l.estado_operativo_lote, '')                                  AS estado,
               l.merma_unidades,
               l.merma_kilos,
               jsonb_strip_nulls(jsonb_build_object(
                   'raza',                      l.raza,
                   'anoTablaGenetica',          l.ano_tabla_genetica,
                   'codigoGuiaGenetica',        l.codigo_guia_genetica,
                   'diasAlimentoPrevioEncaset', (SELECT c2.dias_alimento_previo_encaset
                                                   FROM companies c2 WHERE c2.id = l.company_id),
                   'guiaEcuadorHeaderId',       (SELECT h.id
                                                   FROM guia_genetica_ecuador_header h
                                                  WHERE h.company_id = l.company_id
                                                    AND h.deleted_at IS NULL
                                                    AND h.estado = 'active'
                                                    AND h.anio_guia = l.ano_tabla_genetica
                                                    AND h.raza ILIKE l.raza
                                                  ORDER BY h.id
                                                  LIMIT 1)
               ))                                                                      AS metadata
          FROM lote_ave_engorde l
         WHERE l.lote_ave_engorde_id = p_lote_id
           AND l.deleted_at IS NULL
    ),
    filas AS (
        -- row_number con el MISMO ORDER BY del SELECT final de la fn: `orden` reproduce
        -- exactamente el orden que vio el usuario.
        SELECT row_number() OVER (ORDER BY f.fecha, COALESCE(f.seg_id, 0)) AS orden, f.*
          FROM fn_seguimiento_diario_engorde(p_lote_id) f
    ),
    cab AS (
        INSERT INTO liquidacion_lote_engorde_congelada (
            lote_ave_engorde_id, company_id, granja_id, liquidado_at, liquidado_por_user_id,
            congelada_at, origen, fn_version, filas, checksum,
            lote_nombre, estado_operativo_lote, merma_unidades, merma_kilos, metadata,
            created_at, created_by_user_id)
        SELECT lt.lote_ave_engorde_id, lt.company_id, lt.granja_id, lt.liquidado_at, lt.liquidado_por,
               now(), p_origen, 'v13',
               (SELECT COUNT(*)::int FROM filas),
               COALESCE((SELECT md5(string_agg(x::text, '|' ORDER BY x.orden)) FROM filas x), md5('')),
               lt.lote_nombre, lt.estado, lt.merma_unidades, lt.merma_kilos, lt.metadata,
               now(), p_user
          FROM lote lt
        RETURNING id
    ),
    det AS (
        INSERT INTO liquidacion_lote_engorde_congelada_fila (
            liquidacion_id, orden,
            seg_id, fecha, edad_dia, semana,
            mortalidad_hembras, mortalidad_machos, sel_h, sel_m,
            error_sexaje_hembras, error_sexaje_machos,
            total_mort_sel_dia, perdidas_totales_dia,
            consumo_kg_hembras, consumo_kg_machos, consumo_dia_kg,
            acum_consumo_kg, saldo_aves, pct_perdidas_dia, saldo_alimento_kg,
            ingreso_alimento_kg, traslado_entrada_kg, traslado_salida_kg, consumo_bodega_kg,
            documento, despacho_hembras, despacho_machos, despacho_mixtas,
            despacho_peso_neto, despacho_peso_tara, despacho_promedio_peso_ave,
            tipo_alimento, peso_prom_hembras, peso_prom_machos,
            uniformidad_hembras, uniformidad_machos, cv_hembras, cv_machos,
            consumo_agua_diario, consumo_agua_ph, consumo_agua_orp, consumo_agua_temperatura,
            observaciones, ciclo, metadata, items_adicionales, historico_consumo_alimento,
            created_by_user_id)
        SELECT (SELECT id FROM cab), fl.orden,
               fl.seg_id, fl.fecha, fl.edad_dia, fl.semana,
               fl.mortalidad_hembras, fl.mortalidad_machos, fl.sel_h, fl.sel_m,
               fl.error_sexaje_hembras, fl.error_sexaje_machos,
               fl.total_mort_sel_dia, fl.perdidas_totales_dia,
               fl.consumo_kg_hembras, fl.consumo_kg_machos, fl.consumo_dia_kg,
               fl.acum_consumo_kg, fl.saldo_aves, fl.pct_perdidas_dia, fl.saldo_alimento_kg,
               fl.ingreso_alimento_kg, fl.traslado_entrada_kg, fl.traslado_salida_kg, fl.consumo_bodega_kg,
               fl.documento, fl.despacho_hembras, fl.despacho_machos, fl.despacho_mixtas,
               fl.despacho_peso_neto, fl.despacho_peso_tara, fl.despacho_promedio_peso_ave,
               fl.tipo_alimento, fl.peso_prom_hembras, fl.peso_prom_machos,
               fl.uniformidad_hembras, fl.uniformidad_machos, fl.cv_hembras, fl.cv_machos,
               fl.consumo_agua_diario, fl.consumo_agua_ph, fl.consumo_agua_orp, fl.consumo_agua_temperatura,
               fl.observaciones, fl.ciclo, fl.metadata, fl.items_adicionales, fl.historico_consumo_alimento,
               fl.created_by_user_id
          FROM filas fl
        RETURNING 1
    )
    SELECT id INTO v_id FROM cab;

    IF v_id IS NULL THEN
        RAISE EXCEPTION 'No se pudo congelar la liquidación del lote %: el lote no existe o está eliminado.', p_lote_id;
    END IF;
    RETURN v_id;
END
$fn$;
""");

            // ── 3b. fn_anular_liquidacion_engorde ─────────────────────────────────────────────
            migrationBuilder.Sql("""
CREATE OR REPLACE FUNCTION fn_anular_liquidacion_engorde(p_lote_id INT, p_user TEXT, p_motivo TEXT)
RETURNS INT
LANGUAGE plpgsql
AS $fn$
DECLARE
    v_n INT;
BEGIN
    UPDATE liquidacion_lote_engorde_congelada
       SET anulada_at          = now(),
           anulada_por_user_id = p_user,
           anulada_motivo      = p_motivo
     WHERE lote_ave_engorde_id = p_lote_id
       AND anulada_at IS NULL;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    RETURN v_n;
END
$fn$;
""");

            // ── 3c. fn_recongelar_liquidacion_engorde ─────────────────────────────────────────
            //  Anula la vigente y congela de nuevo con la fórmula de HOY, sin reabrir el lote.
            //  El estado sigue 'Cerrado' ⇒ la foto nueva conserva el cierre en 0 por construcción.
            migrationBuilder.Sql("""
CREATE OR REPLACE FUNCTION fn_recongelar_liquidacion_engorde(p_lote_id INT, p_user TEXT, p_origen TEXT DEFAULT 'recongelado')
RETURNS BIGINT
LANGUAGE plpgsql
AS $fn$
BEGIN
    PERFORM fn_anular_liquidacion_engorde(
        p_lote_id, p_user, 'Re-congelado: la copia se regenera con la fórmula vigente');
    -- Statement nuevo => snapshot nuevo: fn_seguimiento_diario_engorde ya no ve copia vigente
    -- y vuelve a calcular en vivo para tomar la foto.
    RETURN fn_congelar_liquidacion_engorde(p_lote_id, p_user, p_origen);
END
$fn$;
""");

            // ── 4. Trigger: la BD garantiza «Cerrado ⟺ copia vigente», no la disciplina de C# ──
            //  AbrirLoteAsync anula PRIMERO con usuario+motivo reales (acá no encuentra nada);
            //  un UPDATE crudo en BD cae en esta red. Idempotente: WHERE anulada_at IS NULL.
            migrationBuilder.Sql("""
CREATE OR REPLACE FUNCTION fn_trg_lote_ave_engorde_anula_congelada()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
    UPDATE liquidacion_lote_engorde_congelada
       SET anulada_at          = now(),
           anulada_por_user_id = COALESCE(NULLIF(TRIM(NEW.reabierto_por_user_id), ''),
                                          NEW.updated_by_user_id::text,
                                          'trigger'),
           anulada_motivo      = COALESCE('Reapertura: ' || NULLIF(TRIM(NEW.motivo_reapertura), ''),
                                          'El estado del lote dejó de ser Cerrado')
     WHERE lote_ave_engorde_id = NEW.lote_ave_engorde_id
       AND anulada_at IS NULL;
    RETURN NEW;
END
$fn$;

DROP TRIGGER IF EXISTS trg_lote_ave_engorde_anula_congelada ON lote_ave_engorde;
CREATE TRIGGER trg_lote_ave_engorde_anula_congelada
AFTER UPDATE OF estado_operativo_lote ON lote_ave_engorde
FOR EACH ROW
WHEN (LOWER(COALESCE(NEW.estado_operativo_lote, '')) <> 'cerrado')
EXECUTE FUNCTION fn_trg_lote_ave_engorde_anula_congelada();
""");

            // ── 5. fn_seguimiento_diario_engorde v13 (cuerpo v12 VERBATIM + rama congelada,
            //       LANGUAGE sql para conservar el inlining — ver doc del partial .Fn.cs) ───────
            migrationBuilder.Sql(FnSeguimientoDiarioEngordeV13);

            // ── 6. Backfill: congelar los lotes que YA están 'Cerrado' ───────────────────────
            //  Sin copia siguen recalculando y pueden volver a moverse en el próximo fix de la fn
            //  (el escenario que motivó todo). Los REABIERTOS no se congelan (filtro por estado,
            //  jamás por liquidado_at: la reapertura no la limpia). Cada PERFORM es un statement
            //  aparte ⇒ snapshot limpio por lote. Idempotente por NOT EXISTS.
            migrationBuilder.Sql("""
DO $do$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT l.lote_ave_engorde_id
               FROM lote_ave_engorde l
              WHERE LOWER(COALESCE(l.estado_operativo_lote, '')) = 'cerrado'
                AND l.deleted_at IS NULL
                AND NOT EXISTS (SELECT 1
                                  FROM liquidacion_lote_engorde_congelada c
                                 WHERE c.lote_ave_engorde_id = l.lote_ave_engorde_id
                                   AND c.anulada_at IS NULL)
              ORDER BY l.lote_ave_engorde_id
    LOOP
        PERFORM fn_congelar_liquidacion_engorde(r.lote_ave_engorde_id, 'backfill', 'backfill');
    END LOOP;
END
$do$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TRIGGER IF EXISTS trg_lote_ave_engorde_anula_congelada ON lote_ave_engorde;");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS fn_trg_lote_ave_engorde_anula_congelada();");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS fn_recongelar_liquidacion_engorde(INT, TEXT, TEXT);");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS fn_anular_liquidacion_engorde(INT, TEXT, TEXT);");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS fn_congelar_liquidacion_engorde(INT, TEXT, TEXT);");

            // La fn vuelve a la v12 (LANGUAGE sql, sin rama congelada): rollback completo del
            // comportamiento de lectura.
            migrationBuilder.Sql(FnSeguimientoDiarioEngordeV12);

            migrationBuilder.Sql("DROP TABLE IF EXISTS liquidacion_lote_engorde_congelada_fila;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS liquidacion_lote_engorde_congelada;");
        }
    }
}
