// <auto-generated: SQL desde backend/sql/fn_migracion_seguimiento.sql (bloque PRODUCCIÓN) />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// fn_migracion_seguimiento_produccion con los CAMPOS COMPLETOS del modal de producción:
    /// error de sexaje (ya viajaba), pesaje corporal (peso_h/peso_m, uniformidad, coeficiente de
    /// variación, observaciones de pesaje) y los 4 campos de AGUA (consumo_agua_diario/ph/orp/
    /// temperatura). Claves jsonb ADITIVAS y misma firma ⇒ CREATE OR REPLACE sin DROP; un archivo
    /// viejo sigue funcionando byte a byte (las claves ausentes llegan NULL y el merge las conserva).
    /// Además CAE el filtro l.fase = Produccion del INSERT (el cierre de levante nunca actualiza
    /// lotes.fase y bloqueaba la carga del lote cerrado; el JOIN al LPP vivo es el criterio real).
    /// El bloque de LEVANTE no cambia. Fuente canónica: backend/sql/fn_migracion_seguimiento.sql.
    /// </summary>
    public partial class FnMigracionProduccionCamposCompletos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
-- ── PRODUCCIÓN ───────────────────────────────────────────────────────────────
-- Nota de contrato del CONSUMO:
--   cons_separado IS NOT TRUE (default, y lo único que existía antes) → el consumo TOTAL va en
--     cons_kg_h y cons_kg_m queda en 0. Es lo que hacía la carga masiva desde su primera versión y
--     lo que ya está cargado en los históricos: se conserva byte a byte.
--   cons_separado = true → cons_kg_h y cons_kg_m se persisten POR SEXO, igual que
--     ProduccionService.CrearSeguimientoAsync cuando el día trae ítems de alimento por sexo. C# lo
--     manda en true solo cuando la fila del Excel trae ""Alimento 1/2 H-M"", que es justo el caso en
--     que el desglose por sexo existe de verdad.
-- Fix (aves-fix, paridad con Levante): descuento INCREMENTAL igual semántica que el alta manual
-- (SeguimientoProduccionService.AplicarDescuentoLppAsync) — NO se recalcula aves_h_actual/aves_m_actual
-- desde cero, porque ese campo también lo tocan los traslados entre lotes de Producción
-- (TrasladoAvesDesdeSegService, rama Producción↔Producción) y el módulo Movimiento de Aves
-- (MovimientoAvesService.Postura.cs), que no dejan mortalidad/sel/error en esta tabla. Un
-- recálculo total pisaría esos ajustes. Además, si la fecha ya tiene una fila ""solo traslado""
-- (es_traslado=true, sin datos manuales) se completa (merge) en vez de saltear la fila del Excel
-- en silencio — mismo criterio que el merge manual (""Feature 14"" en SeguimientoProduccionService).
-- Importante: las filas de traslado NO setean lote_postura_produccion_id (ver
-- TrasladoAvesDesdeSegService), así que el matching es por lote_id crudo + fecha calendario, no
-- por lote_postura_produccion_id (el dedup original por ese FK nunca encontraba esas filas).
CREATE OR REPLACE FUNCTION public.fn_migracion_seguimiento_produccion(
    p_company_id integer,
    p_usuario    integer,
    p_rows       jsonb
) RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    v_actualizados integer := 0;
    v_arrastre     integer := 0;
    v_insertados   integer := 0;
BEGIN
    DROP TABLE IF EXISTS tmp_filas_prod;
    DROP TABLE IF EXISTS tmp_delta_prod;

    CREATE TEMP TABLE tmp_filas_prod ON COMMIT DROP AS
    SELECT * FROM jsonb_to_recordset(p_rows) AS x(
        lote_id  integer,
        fecha    date,
        mort_h integer, mort_m integer,
        sel_h  integer, sel_m  integer,
        err_h  integer, err_m  integer,
        cons_h numeric, cons_m numeric,
        huevo_tot integer, huevo_inc integer, peso_huevo double precision,
        etapa integer, observaciones text,
        -- ── aditivo ──
        metadata jsonb,
        tipo_alimento text,
        cons_separado boolean,
        es_merge_arrastre boolean,
        huevo_limpio integer, huevo_tratado integer, huevo_sucio integer,
        huevo_deforme integer, huevo_blanco integer, huevo_doble_yema integer,
        huevo_piso integer, huevo_pequeno integer, huevo_roto integer,
        huevo_desecho integer, huevo_otro integer,
        -- ── aditivo (campos completos del modal: pesaje corporal + agua) ──
        peso_h numeric, peso_m numeric,
        uniformidad numeric, coef_variacion numeric, obs_pesaje text,
        agua_diario double precision, agua_ph double precision,
        agua_orp double precision, agua_temp double precision
    );

    CREATE TEMP TABLE tmp_delta_prod (lote_postura_produccion_id integer, h integer, m integer) ON COMMIT DROP;

    -- Paso 0: MERGE sobre la fila del ARRASTRE DE HUEVOS DEL LEVANTE.
    -- Al cerrar el levante se crea una fila de producción con los huevos arrastrados (y nada más). Si
    -- el Excel trae ESE MISMO día — el caso normal, porque es el primer día de producción — hay que
    -- fusionarlo, igual que hace el alta manual (ProduccionService.AplicarRequestSobreFilaArrastre):
    -- los huevos se SUMAN y el resto de los campos los define el registro. Sin este paso el día se
    -- omitía en silencio y se perdían mortalidad, consumo y clasificación de la carga.
    -- Los huevos llegan YA SUMADOS desde C# (que es quien sabe leer la marca del metadata), así que
    -- acá es un UPDATE directo; el metadata también viene con la marca conservada y la ventana de
    -- merge ya cerrada (seguimientoRegistrado), para que el arrastre siga siendo idempotente.
    WITH upd_arr AS (
        UPDATE public.seguimiento_diario_produccion sd
        SET mortalidad_hembras   = COALESCE(f.mort_h,0),
            mortalidad_machos    = COALESCE(f.mort_m,0),
            sel_h                = COALESCE(f.sel_h,0),
            sel_m                = COALESCE(f.sel_m,0),
            error_sexaje_hembras = COALESCE(f.err_h,0),
            error_sexaje_machos  = COALESCE(f.err_m,0),
            cons_kg_h            = CASE WHEN f.cons_separado IS TRUE
                                        THEN COALESCE(f.cons_h,0)
                                        ELSE (COALESCE(f.cons_h,0) + COALESCE(f.cons_m,0)) END,
            cons_kg_m            = CASE WHEN f.cons_separado IS TRUE THEN COALESCE(f.cons_m,0) ELSE 0 END,
            tipo_alimento        = COALESCE(f.tipo_alimento, sd.tipo_alimento),
            huevo_tot            = COALESCE(f.huevo_tot,0),
            huevo_inc            = COALESCE(f.huevo_inc,0),
            peso_huevo           = COALESCE(f.peso_huevo, sd.peso_huevo),
            etapa                = COALESCE(f.etapa,1),
            observaciones        = f.observaciones,
            metadata             = COALESCE(f.metadata, sd.metadata),
            huevo_limpio         = COALESCE(f.huevo_limpio,0),
            huevo_tratado        = COALESCE(f.huevo_tratado,0),
            huevo_sucio          = COALESCE(f.huevo_sucio,0),
            huevo_deforme        = COALESCE(f.huevo_deforme,0),
            huevo_blanco         = COALESCE(f.huevo_blanco,0),
            huevo_doble_yema     = COALESCE(f.huevo_doble_yema,0),
            huevo_piso           = COALESCE(f.huevo_piso,0),
            huevo_pequeno        = COALESCE(f.huevo_pequeno,0),
            huevo_roto           = COALESCE(f.huevo_roto,0),
            huevo_desecho        = COALESCE(f.huevo_desecho,0),
            huevo_otro           = COALESCE(f.huevo_otro,0),
            peso_h               = COALESCE(f.peso_h, sd.peso_h),
            peso_m               = COALESCE(f.peso_m, sd.peso_m),
            uniformidad          = COALESCE(f.uniformidad, sd.uniformidad),
            coeficiente_variacion = COALESCE(f.coef_variacion, sd.coeficiente_variacion),
            observaciones_pesaje = COALESCE(f.obs_pesaje, sd.observaciones_pesaje),
            consumo_agua_diario  = COALESCE(f.agua_diario, sd.consumo_agua_diario),
            consumo_agua_ph      = COALESCE(f.agua_ph, sd.consumo_agua_ph),
            consumo_agua_orp     = COALESCE(f.agua_orp, sd.consumo_agua_orp),
            consumo_agua_temperatura = COALESCE(f.agua_temp, sd.consumo_agua_temperatura),
            updated_by_user_id   = p_usuario,
            updated_at           = (NOW() AT TIME ZONE 'utc')
        FROM tmp_filas_prod f
        JOIN public.lote_postura_produccion lpp0
          ON lpp0.lote_id = f.lote_id AND lpp0.deleted_at IS NULL AND lpp0.company_id = p_company_id
        WHERE f.es_merge_arrastre IS TRUE
          AND sd.lote_id = f.lote_id
          AND sd.fecha_registro::date = f.fecha
        RETURNING lpp0.lote_postura_produccion_id,
                  COALESCE(f.mort_h,0) + COALESCE(f.sel_h,0) + COALESCE(f.err_h,0) AS h,
                  COALESCE(f.mort_m,0) + COALESCE(f.sel_m,0) + COALESCE(f.err_m,0) AS m
    )
    INSERT INTO tmp_delta_prod SELECT lote_postura_produccion_id, h, m FROM upd_arr;
    GET DIAGNOSTICS v_arrastre = ROW_COUNT;

    -- Paso 1: completar filas ""solo traslado"" existentes con los datos históricos (merge).
    WITH upd AS (
        UPDATE public.seguimiento_diario_produccion sd
        SET mortalidad_hembras   = COALESCE(f.mort_h,0),
            mortalidad_machos    = COALESCE(f.mort_m,0),
            sel_h                = COALESCE(f.sel_h,0),
            sel_m                = COALESCE(f.sel_m,0),
            error_sexaje_hembras = COALESCE(f.err_h,0),
            error_sexaje_machos  = COALESCE(f.err_m,0),
            cons_kg_h            = CASE WHEN f.cons_separado IS TRUE
                                        THEN COALESCE(f.cons_h,0)
                                        ELSE (COALESCE(f.cons_h,0) + COALESCE(f.cons_m,0)) END,
            cons_kg_m            = CASE WHEN f.cons_separado IS TRUE THEN COALESCE(f.cons_m,0) ELSE 0 END,
            tipo_alimento        = COALESCE(f.tipo_alimento, sd.tipo_alimento),
            huevo_tot            = COALESCE(f.huevo_tot,0),
            huevo_inc            = COALESCE(f.huevo_inc,0),
            peso_huevo           = f.peso_huevo,
            etapa                = COALESCE(f.etapa,1),
            observaciones        = f.observaciones,
            metadata             = COALESCE(f.metadata, sd.metadata),
            huevo_limpio         = COALESCE(f.huevo_limpio, sd.huevo_limpio),
            huevo_tratado        = COALESCE(f.huevo_tratado, sd.huevo_tratado),
            huevo_sucio          = COALESCE(f.huevo_sucio, sd.huevo_sucio),
            huevo_deforme        = COALESCE(f.huevo_deforme, sd.huevo_deforme),
            huevo_blanco         = COALESCE(f.huevo_blanco, sd.huevo_blanco),
            huevo_doble_yema     = COALESCE(f.huevo_doble_yema, sd.huevo_doble_yema),
            huevo_piso           = COALESCE(f.huevo_piso, sd.huevo_piso),
            huevo_pequeno        = COALESCE(f.huevo_pequeno, sd.huevo_pequeno),
            huevo_roto           = COALESCE(f.huevo_roto, sd.huevo_roto),
            huevo_desecho        = COALESCE(f.huevo_desecho, sd.huevo_desecho),
            huevo_otro           = COALESCE(f.huevo_otro, sd.huevo_otro),
            peso_h               = COALESCE(f.peso_h, sd.peso_h),
            peso_m               = COALESCE(f.peso_m, sd.peso_m),
            uniformidad          = COALESCE(f.uniformidad, sd.uniformidad),
            coeficiente_variacion = COALESCE(f.coef_variacion, sd.coeficiente_variacion),
            observaciones_pesaje = COALESCE(f.obs_pesaje, sd.observaciones_pesaje),
            consumo_agua_diario  = COALESCE(f.agua_diario, sd.consumo_agua_diario),
            consumo_agua_ph      = COALESCE(f.agua_ph, sd.consumo_agua_ph),
            consumo_agua_orp     = COALESCE(f.agua_orp, sd.consumo_agua_orp),
            consumo_agua_temperatura = COALESCE(f.agua_temp, sd.consumo_agua_temperatura),
            updated_by_user_id   = p_usuario,
            updated_at           = (NOW() AT TIME ZONE 'utc')
        FROM tmp_filas_prod f
        JOIN public.lote_postura_produccion lpp2
          ON lpp2.lote_id = f.lote_id AND lpp2.deleted_at IS NULL AND lpp2.company_id = p_company_id
        WHERE sd.lote_id = f.lote_id
          AND sd.fecha_registro::date = f.fecha
          AND sd.es_traslado = true
          AND COALESCE(sd.mortalidad_hembras,0) = 0 AND COALESCE(sd.mortalidad_machos,0) = 0
          AND COALESCE(sd.sel_h,0) = 0 AND COALESCE(sd.sel_m,0) = 0
          AND COALESCE(sd.error_sexaje_hembras,0) = 0 AND COALESCE(sd.error_sexaje_machos,0) = 0
          AND COALESCE(sd.cons_kg_h,0) = 0 AND COALESCE(sd.cons_kg_m,0) = 0
          AND COALESCE(sd.huevo_tot,0) = 0
        RETURNING lpp2.lote_postura_produccion_id,
                  COALESCE(f.mort_h,0) + COALESCE(f.sel_h,0) + COALESCE(f.err_h,0) AS h,
                  COALESCE(f.mort_m,0) + COALESCE(f.sel_m,0) + COALESCE(f.err_m,0) AS m
    )
    INSERT INTO tmp_delta_prod SELECT lote_postura_produccion_id, h, m FROM upd;
    GET DIAGNOSTICS v_actualizados = ROW_COUNT;

    -- Paso 2: insertar filas nuevas (fechas sin ninguna fila previa para el lote).
    WITH ins AS (
        INSERT INTO public.seguimiento_diario_produccion (
            lote_id, lote_postura_produccion_id, fecha_registro,
            mortalidad_hembras, mortalidad_machos, sel_h, sel_m,
            error_sexaje_hembras, error_sexaje_machos,
            cons_kg_h, cons_kg_m, tipo_alimento,
            huevo_tot, huevo_inc, peso_huevo, etapa, observaciones,
            company_id, created_by_user_id, created_at,
            metadata,
            huevo_limpio, huevo_tratado, huevo_sucio, huevo_deforme, huevo_blanco,
            huevo_doble_yema, huevo_piso, huevo_pequeno, huevo_roto, huevo_desecho, huevo_otro,
            peso_h, peso_m, uniformidad, coeficiente_variacion, observaciones_pesaje,
            consumo_agua_diario, consumo_agua_ph, consumo_agua_orp, consumo_agua_temperatura
        )
        SELECT
            f.lote_id, lpp.lote_postura_produccion_id, f.fecha::timestamptz,
            COALESCE(f.mort_h,0), COALESCE(f.mort_m,0), COALESCE(f.sel_h,0), COALESCE(f.sel_m,0),
            COALESCE(f.err_h,0), COALESCE(f.err_m,0),
            CASE WHEN f.cons_separado IS TRUE
                 THEN COALESCE(f.cons_h,0)
                 ELSE (COALESCE(f.cons_h,0) + COALESCE(f.cons_m,0)) END,
            CASE WHEN f.cons_separado IS TRUE THEN COALESCE(f.cons_m,0) ELSE 0 END,
            COALESCE(f.tipo_alimento,''),
            COALESCE(f.huevo_tot,0), COALESCE(f.huevo_inc,0), f.peso_huevo, COALESCE(f.etapa,1), f.observaciones,
            p_company_id, p_usuario, (NOW() AT TIME ZONE 'utc'),
            f.metadata,
            COALESCE(f.huevo_limpio,0), COALESCE(f.huevo_tratado,0), COALESCE(f.huevo_sucio,0),
            COALESCE(f.huevo_deforme,0), COALESCE(f.huevo_blanco,0), COALESCE(f.huevo_doble_yema,0),
            COALESCE(f.huevo_piso,0), COALESCE(f.huevo_pequeno,0), COALESCE(f.huevo_roto,0),
            COALESCE(f.huevo_desecho,0), COALESCE(f.huevo_otro,0),
            f.peso_h, f.peso_m, f.uniformidad, f.coef_variacion, f.obs_pesaje,
            f.agua_diario, f.agua_ph, f.agua_orp, f.agua_temp
        -- Sin filtro por l.fase: el cierre de levante NUNCA actualiza lotes.fase (queda 'Levante')
        -- y con el filtro un lote cerrado por el flujo normal no podía cargar producción por Excel.
        -- La definición operativa de ""producción"" es la existencia del LPP vivo (mismo criterio que
        -- DeterminarFaseLote), y ese JOIN ya está acá; la elegibilidad C# además exige
        -- Levante Cerrado + liquidado.
        FROM tmp_filas_prod f
        JOIN public.lotes l
          ON l.lote_id = f.lote_id AND l.company_id = p_company_id AND l.deleted_at IS NULL
        JOIN public.lote_postura_produccion lpp
          ON lpp.lote_id = f.lote_id AND lpp.deleted_at IS NULL
        WHERE NOT EXISTS (
            SELECT 1 FROM public.seguimiento_diario_produccion sd
            WHERE sd.lote_id = f.lote_id
              AND sd.fecha_registro::date = f.fecha
        )
        RETURNING lote_postura_produccion_id,
                  COALESCE(mortalidad_hembras,0) + COALESCE(sel_h,0) + COALESCE(error_sexaje_hembras,0) AS h,
                  COALESCE(mortalidad_machos,0)  + COALESCE(sel_m,0) + COALESCE(error_sexaje_machos,0)  AS m
    )
    INSERT INTO tmp_delta_prod SELECT lote_postura_produccion_id, h, m FROM ins;
    GET DIAGNOSTICS v_insertados = ROW_COUNT;

    -- Paso 3: descuento INCREMENTAL sobre el valor actual (no recálculo total) —
    -- conserva cualquier ajuste ya reflejado por traslados o movimientos de aves.
    UPDATE public.lote_postura_produccion lpp
    SET aves_h_actual = GREATEST(0, COALESCE(lpp.aves_h_actual, lpp.aves_h_inicial, lpp.hembras_iniciales_prod, 0) - sub.h),
        aves_m_actual = GREATEST(0, COALESCE(lpp.aves_m_actual, lpp.aves_m_inicial, lpp.machos_iniciales_prod, 0) - sub.m),
        updated_at    = (NOW() AT TIME ZONE 'utc')
    FROM (
        SELECT lote_postura_produccion_id, SUM(h) AS h, SUM(m) AS m
        FROM tmp_delta_prod
        WHERE lote_postura_produccion_id IS NOT NULL
        GROUP BY lote_postura_produccion_id
    ) sub
    WHERE lpp.lote_postura_produccion_id = sub.lote_postura_produccion_id
      AND (sub.h <> 0 OR sub.m <> 0);

    RETURN v_arrastre + v_actualizados + v_insertados;
END;
$$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Sin Down automático: la versión previa vive en la migración
            // 20260728140000_FnMigracionProduccionMergeArrastreHuevos (re-aplicarla a mano si hiciera falta).
        }
    }
}
