using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// F7.3 — <c>lote_huevo_items</c>: qué tipos de huevo produce cada lote. El seguimiento diario de
    /// PRODUCCIÓN muestra una fila fija por cada uno y rechaza cualquier ítem que no esté acá.
    /// </summary>
    /// <remarks>
    /// <b>Fail-closed por decisión del cliente</b> (21-ago-2026): un lote sin ítems declarados no
    /// puede clasificar huevos — no se cae al catálogo completo. Por eso la tabla nace VACÍA y no
    /// se siembra con «todos los ítems de cada lote»: sembrarla sería exactamente el comportamiento
    /// que se pidió eliminar.
    ///
    /// <b>Radio de impacto CERO, medido.</b> Santa Reyes es la única empresa con
    /// <c>clasificacion_huevo_por_items = true</c> y tiene 0 lotes; en toda la base hay 0
    /// seguimientos con <c>metadata.huevoItems</c>. Las otras 4 empresas tienen el flag apagado, y
    /// el gate que consume esta tabla vive detrás de ese flag, así que no las toca.
    ///
    /// <b>Espeja <c>lote_silos</c></b> (migración <c>20260812224755</c>), el patrón canónico de N:M
    /// por lote del repo: cuelga de <c>lotes.lote_id</c> —el maestro, la única fila que existe en
    /// levante y en producción— y no de los espejos de etapa, así que la declaración sobrevive al
    /// cierre del levante sin tener que copiarse.
    ///
    /// FK a <c>catalogo_items</c> con <c>ON DELETE RESTRICT</c>: un ítem que algún lote declara no se
    /// borra de la base. Para sacarlo de circulación está <c>activo</c>, que es el camino que ya usa
    /// el CRUD de catálogo.
    ///
    /// <b>Idempotente:</b> <c>CREATE TABLE IF NOT EXISTS</c> + <c>CREATE INDEX IF NOT EXISTS</c>.
    /// </remarks>
    public partial class AddLoteHuevoItems : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.lote_huevo_items (
    id                 integer     GENERATED BY DEFAULT AS IDENTITY,
    company_id         integer     NOT NULL,
    lote_id            integer     NOT NULL,
    catalog_item_id    integer     NOT NULL,
    activo             boolean     NOT NULL DEFAULT TRUE,
    created_at         timestamptz NOT NULL,
    created_by_user_id uuid        NULL,
    CONSTRAINT pk_lote_huevo_items PRIMARY KEY (id),
    CONSTRAINT fk_lote_huevo_items_lote FOREIGN KEY (lote_id)
        REFERENCES public.lotes (lote_id) ON DELETE CASCADE,
    CONSTRAINT fk_lote_huevo_items_item FOREIGN KEY (catalog_item_id)
        REFERENCES public.catalogo_items (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lote_huevo_items_lote_item
    ON public.lote_huevo_items (lote_id, catalog_item_id);
CREATE INDEX IF NOT EXISTS ix_lote_huevo_items_item
    ON public.lote_huevo_items (catalog_item_id);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.lote_huevo_items;");
        }
    }
}
