using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// FASE A de «inventario por silo» (Santa Reyes). Solo ESTRUCTURA: crea el catálogo de silos y
    /// las dos tablas de asignación, y agrega el flag de empresa. <b>No toca el inventario</b>
    /// (<c>inventario_gestion_stock</c> / <c>_movimiento</c> quedan intactos) ⇒ riesgo nulo para las
    /// empresas que ya operan.
    ///
    /// <list type="bullet">
    ///   <item><c>companies.maneja_inventario_por_silo</c> — flag por comportamiento, default false.</item>
    ///   <item><c>silo_catalogo</c> — lista maestra de silos por empresa (1..100).</item>
    ///   <item><c>farm_silos</c> — gana <c>silo_catalogo_id</c>, <c>updated_at</c> y <c>deleted_at</c>
    ///         (baja lógica). Su índice único pasa a filtrarse por <c>deleted_at IS NULL</c> para que
    ///         un silo dado de baja no bloquee reusar su nombre.</item>
    ///   <item><c>galpon_silos</c> — N:M galpón ↔ silo (qué silos alimentan al galpón).</item>
    ///   <item><c>lote_silos</c> — N:M lote ↔ silo (de qué silos consume el lote).</item>
    /// </list>
    ///
    /// <para>
    /// <b>Escrita a mano en SQL idempotente</b> (regla del repo): el deploy la aplica sola al arrancar
    /// y tiene que poder correr sobre una BD donde algo de esto ya exista sin abortar el arranque.
    /// El efecto es idéntico al que generó EF.
    /// </para>
    /// </summary>
    public partial class AddInventarioPorSiloCatalogoYAsignaciones : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── Flag de empresa ──────────────────────────────────────────────────
            migrationBuilder.Sql(@"
ALTER TABLE public.companies
    ADD COLUMN IF NOT EXISTS maneja_inventario_por_silo boolean NOT NULL DEFAULT false;
");

            // ── Lista maestra de silos (1..100 por empresa) ──────────────────────
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.silo_catalogo (
    id          integer      GENERATED BY DEFAULT AS IDENTITY,
    company_id  integer      NOT NULL,
    numero      integer      NOT NULL,
    nombre      varchar(120) NOT NULL,
    descripcion varchar(200) NULL,
    activo      boolean      NOT NULL DEFAULT TRUE,
    created_at  timestamptz  NOT NULL,
    updated_at  timestamptz  NULL,
    deleted_at  timestamptz  NULL,
    CONSTRAINT pk_silo_catalogo PRIMARY KEY (id),
    CONSTRAINT fk_silo_catalogo_company FOREIGN KEY (company_id)
        REFERENCES public.companies (id) ON DELETE RESTRICT
);

-- Únicos entre los NO borrados: una baja lógica no puede impedir reusar el número/nombre.
CREATE UNIQUE INDEX IF NOT EXISTS ux_silo_catalogo_company_numero
    ON public.silo_catalogo (company_id, numero) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_silo_catalogo_company_nombre
    ON public.silo_catalogo (company_id, nombre) WHERE deleted_at IS NULL;
");

            // ── farm_silos: baja lógica + vínculo al catálogo ────────────────────
            migrationBuilder.Sql(@"
ALTER TABLE public.farm_silos
    ADD COLUMN IF NOT EXISTS silo_catalogo_id integer     NULL,
    ADD COLUMN IF NOT EXISTS updated_at       timestamptz NULL,
    ADD COLUMN IF NOT EXISTS deleted_at       timestamptz NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_farm_silos_silo_catalogo'
    ) THEN
        ALTER TABLE public.farm_silos
            ADD CONSTRAINT fk_farm_silos_silo_catalogo FOREIGN KEY (silo_catalogo_id)
                REFERENCES public.silo_catalogo (id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_farm_silos_silo_catalogo_id
    ON public.farm_silos (silo_catalogo_id);

-- El único de (granja, nombre) pasa a filtrarse por deleted_at. Hoy todas las filas tienen
-- deleted_at NULL, así que qué colisiona no cambia: solo deja de bloquear a futuro.
DROP INDEX IF EXISTS public.ux_farm_silos_granja_nombre;
CREATE UNIQUE INDEX IF NOT EXISTS ux_farm_silos_granja_nombre
    ON public.farm_silos (granja_id, nombre) WHERE deleted_at IS NULL;
");

            // ── N:M galpón ↔ silo ────────────────────────────────────────────────
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.galpon_silos (
    id                 integer     GENERATED BY DEFAULT AS IDENTITY,
    company_id         integer     NOT NULL,
    granja_id          integer     NOT NULL,
    nucleo_id          varchar(20) NOT NULL,
    galpon_id          varchar(20) NOT NULL,
    farm_silo_id       integer     NOT NULL,
    activo             boolean     NOT NULL DEFAULT TRUE,
    created_at         timestamptz NOT NULL,
    created_by_user_id uuid        NULL,
    CONSTRAINT pk_galpon_silos PRIMARY KEY (id),
    CONSTRAINT fk_galpon_silos_farm_silo FOREIGN KEY (farm_silo_id)
        REFERENCES public.farm_silos (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_galpon_silos_galpon_silo
    ON public.galpon_silos (granja_id, nucleo_id, galpon_id, farm_silo_id);
CREATE INDEX IF NOT EXISTS ix_galpon_silos_silo
    ON public.galpon_silos (farm_silo_id);
CREATE INDEX IF NOT EXISTS ix_galpon_silos_granja_galpon
    ON public.galpon_silos (granja_id, galpon_id);
");

            // ── N:M lote ↔ silo ──────────────────────────────────────────────────
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.lote_silos (
    id                 integer     GENERATED BY DEFAULT AS IDENTITY,
    company_id         integer     NOT NULL,
    lote_id            integer     NOT NULL,
    farm_silo_id       integer     NOT NULL,
    activo             boolean     NOT NULL DEFAULT TRUE,
    created_at         timestamptz NOT NULL,
    created_by_user_id uuid        NULL,
    CONSTRAINT pk_lote_silos PRIMARY KEY (id),
    CONSTRAINT fk_lote_silos_lote FOREIGN KEY (lote_id)
        REFERENCES public.lotes (lote_id) ON DELETE CASCADE,
    CONSTRAINT fk_lote_silos_silo FOREIGN KEY (farm_silo_id)
        REFERENCES public.farm_silos (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lote_silos_lote_silo
    ON public.lote_silos (lote_id, farm_silo_id);
CREATE INDEX IF NOT EXISTS ix_lote_silos_silo
    ON public.lote_silos (farm_silo_id);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.lote_silos;
DROP TABLE IF EXISTS public.galpon_silos;

ALTER TABLE public.farm_silos DROP CONSTRAINT IF EXISTS fk_farm_silos_silo_catalogo;
DROP INDEX IF EXISTS public.ix_farm_silos_silo_catalogo_id;

DROP TABLE IF EXISTS public.silo_catalogo;

ALTER TABLE public.farm_silos
    DROP COLUMN IF EXISTS silo_catalogo_id,
    DROP COLUMN IF EXISTS updated_at,
    DROP COLUMN IF EXISTS deleted_at;

-- El único vuelve a su forma sin filtro (deleted_at ya no existe).
DROP INDEX IF EXISTS public.ux_farm_silos_granja_nombre;
CREATE UNIQUE INDEX IF NOT EXISTS ux_farm_silos_granja_nombre
    ON public.farm_silos (granja_id, nombre);

ALTER TABLE public.companies DROP COLUMN IF EXISTS maneja_inventario_por_silo;
");
        }
    }
}
