using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Implementación v2: el plan gana <c>tipo</c> (implementacion/capacitacion/mixto), encargado
    /// (<c>implementador_user_id</c>, por defecto el creador) y <c>creado_por_user_guid</c> (guid
    /// real del creador para joinear nombre/correo). Nueva tabla <c>implementacion_tarea_firmas</c>:
    /// participantes de cada tarea (asistentes) que firman el recibido (firma digitada + nota) o
    /// registran una novedad (rechazo con motivo). Up() en SQL crudo idempotente (ADD COLUMN/CREATE
    /// TABLE/INDEX IF NOT EXISTS + constraints guardadas por pg_constraint), 1:1 con el modelo EF
    /// (ver Designer/snapshot generados), siguiendo el patrón de 20260720135027_AddImplementacionModule.
    /// </summary>
    public partial class AddImplementacionFirmasYTipo : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE public.implementacion_planes
                    ADD COLUMN IF NOT EXISTS tipo character varying(20) NOT NULL DEFAULT 'implementacion';
                ALTER TABLE public.implementacion_planes
                    ADD COLUMN IF NOT EXISTS implementador_user_id uuid NULL;
                ALTER TABLE public.implementacion_planes
                    ADD COLUMN IF NOT EXISTS creado_por_user_guid uuid NULL;

                CREATE TABLE IF NOT EXISTS public.implementacion_tarea_firmas (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    tarea_id integer NOT NULL,
                    user_id uuid NOT NULL,
                    estado character varying(20) NOT NULL DEFAULT 'pendiente',
                    firma_texto character varying(300) NULL,
                    nota character varying(2000) NULL,
                    fecha_respuesta timestamp with time zone NULL,
                    company_id integer NOT NULL,
                    created_by_user_id integer NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_by_user_id integer NULL,
                    updated_at timestamp with time zone NULL,
                    deleted_at timestamp with time zone NULL,
                    CONSTRAINT pk_implementacion_tarea_firmas PRIMARY KEY (id),
                    CONSTRAINT ck_implementacion_firma_estado
                        CHECK (estado IN ('pendiente', 'firmada', 'rechazada'))
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'ck_implementacion_plan_tipo') THEN
                        ALTER TABLE public.implementacion_planes
                            ADD CONSTRAINT ck_implementacion_plan_tipo
                            CHECK (tipo IN ('implementacion', 'capacitacion', 'mixto'));
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_planes_users_implementador_user_id') THEN
                        ALTER TABLE public.implementacion_planes
                            ADD CONSTRAINT fk_implementacion_planes_users_implementador_user_id
                            FOREIGN KEY (implementador_user_id) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_planes_users_creado_por_user_guid') THEN
                        ALTER TABLE public.implementacion_planes
                            ADD CONSTRAINT fk_implementacion_planes_users_creado_por_user_guid
                            FOREIGN KEY (creado_por_user_guid) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tarea_firmas_implementacion_tareas_tarea_id') THEN
                        ALTER TABLE public.implementacion_tarea_firmas
                            ADD CONSTRAINT fk_implementacion_tarea_firmas_implementacion_tareas_tarea_id
                            FOREIGN KEY (tarea_id) REFERENCES public.implementacion_tareas (id) ON DELETE CASCADE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tarea_firmas_users_user_id') THEN
                        ALTER TABLE public.implementacion_tarea_firmas
                            ADD CONSTRAINT fk_implementacion_tarea_firmas_users_user_id
                            FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ix_implementacion_planes_implementador
                    ON public.implementacion_planes (implementador_user_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_planes_creado_por_user_guid
                    ON public.implementacion_planes (creado_por_user_guid);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tarea_firmas_tarea
                    ON public.implementacion_tarea_firmas (tarea_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tarea_firmas_user
                    ON public.implementacion_tarea_firmas (user_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tarea_firmas_company
                    ON public.implementacion_tarea_firmas (company_id);
                CREATE UNIQUE INDEX IF NOT EXISTS ux_implementacion_tarea_firmas_tarea_user
                    ON public.implementacion_tarea_firmas (tarea_id, user_id)
                    WHERE deleted_at IS NULL;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS public.implementacion_tarea_firmas;
                ALTER TABLE public.implementacion_planes
                    DROP CONSTRAINT IF EXISTS ck_implementacion_plan_tipo,
                    DROP CONSTRAINT IF EXISTS fk_implementacion_planes_users_implementador_user_id,
                    DROP CONSTRAINT IF EXISTS fk_implementacion_planes_users_creado_por_user_guid;
                ALTER TABLE public.implementacion_planes
                    DROP COLUMN IF EXISTS tipo,
                    DROP COLUMN IF EXISTS implementador_user_id,
                    DROP COLUMN IF EXISTS creado_por_user_guid;
                """);
        }
    }
}
