using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Registro de idempotencia del push offline (PWA F3).
    ///
    /// Escrita con SQL crudo e `IF NOT EXISTS` (regla del repo): el deploy corre las migraciones al
    /// arrancar, y una migración que solo puede correr una vez deja el historial inconsistente si el
    /// contenedor reinicia a mitad.
    ///
    /// 🔴 **`ux_sync_operaciones_client_op_id` es el corazón del módulo.** La unicidad vive en la BASE,
    /// no en el service: un chequeo previo en C# tiene una ventana entre el SELECT y el INSERT, y esa
    /// ventana es exactamente el caso que la idempotencia debe cubrir (dos envíos del mismo lote a la
    /// vez, o un reintento del cliente sobre una respuesta que se perdió en la red). Sin este índice,
    /// una captura de campo se aplica dos veces y la mortalidad se cuenta doble.
    /// </summary>
    public partial class AddSyncOperaciones : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS sync_operaciones (
                    id                        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    client_op_id              uuid                     NOT NULL,
                    tipo                      character varying(60)    NOT NULL,
                    user_id                   integer                  NOT NULL,
                    company_id                integer                  NOT NULL,
                    device_id                 character varying(80)    NULL,
                    capturado_at_dispositivo  timestamp with time zone NULL,
                    estado                    character varying(20)    NOT NULL,
                    error_codigo              character varying(40)    NULL,
                    respuesta_json            jsonb                    NULL,
                    entidad_id                integer                  NULL,
                    recibido_at               timestamp with time zone NOT NULL,
                    CONSTRAINT pk_sync_operaciones PRIMARY KEY (id)
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ix_sync_operaciones_user_recibido
                    ON sync_operaciones (user_id, recibido_at);
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_sync_operaciones_client_op_id
                    ON sync_operaciones (client_op_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS sync_operaciones;");
        }
    }
}
