using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDbStudioGrantsAndAudit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotente (regla del repo): el deploy aplica esto al arrancar y debe ser
            // seguro re-ejecutar aunque las tablas/índices ya existan.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.dbstudio_audit (
                    id              bigint GENERATED BY DEFAULT AS IDENTITY,
                    action          varchar(64)  NOT NULL,
                    schema_name     varchar(128) NULL,
                    object_name     varchar(256) NULL,
                    sql_text        text         NOT NULL,
                    result_summary  jsonb        NOT NULL,
                    success         boolean      NOT NULL,
                    actor_user_id   uuid         NULL,
                    actor_email     varchar(256) NULL,
                    company_id      integer      NOT NULL,
                    ip_address      varchar(64)  NULL,
                    created_at_utc  timestamptz  NOT NULL,
                    CONSTRAINT pk_dbstudio_audit PRIMARY KEY (id)
                );");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.dbstudio_object_grant (
                    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
                    user_id             uuid         NOT NULL,
                    company_id          integer      NOT NULL,
                    schema_name         varchar(128) NOT NULL,
                    object_name         varchar(256) NOT NULL,
                    access_level        integer      NOT NULL,
                    granted_by_user_id  uuid         NOT NULL,
                    granted_at_utc      timestamptz  NOT NULL,
                    CONSTRAINT pk_dbstudio_object_grant PRIMARY KEY (id)
                );");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_dbstudio_audit_actor ON public.dbstudio_audit (actor_user_id);");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_dbstudio_audit_created_at ON public.dbstudio_audit (created_at_utc);");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS ux_dbstudio_grant_user_object ON public.dbstudio_object_grant (user_id, company_id, schema_name, object_name);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "dbstudio_audit",
                schema: "public");

            migrationBuilder.DropTable(
                name: "dbstudio_object_grant",
                schema: "public");
        }
    }
}
