using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Tabla puente lote_base_engorde_granja (M:N lote base ↔ granjas). Parametriza en qué
    /// granjas es visible un lote base al crear un lote de engorde. Idempotente.
    /// </summary>
    public partial class AddLoteBaseEngordeGranja : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.lote_base_engorde_granja (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lote_base_engorde_id integer NOT NULL,
    farm_id integer NOT NULL,
    company_id integer NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_lote_base_engorde_granja PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_lote_base_engorde_granja_farm
    ON public.lote_base_engorde_granja (farm_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lote_base_engorde_granja_base_farm
    ON public.lote_base_engorde_granja (lote_base_engorde_id, farm_id);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.lote_base_engorde_granja;");
        }
    }
}
