using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Motor de flujos de validación parametrizables por empresa (8 tablas), ver
    /// fase_de_desarrollo/flujos_validacion_parametrizables_por_empresa_plan.md §6. DDL idempotente
    /// a mano (no el CreateTable/CreateIndex scaffoldeado): la app corre migraciones pendientes en
    /// cada arranque, así que una migración a medias no puede dejar el historial inconsistente.
    /// </summary>
    public partial class AddFlujosValidacionParametrizables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.validacion_procesos (
    id           integer GENERATED BY DEFAULT AS IDENTITY,
    key          character varying(60)  NOT NULL,
    nombre       character varying(120) NOT NULL,
    descripcion  text NULL,
    adapter_key  character varying(60)  NOT NULL,
    menu_route   character varying(200) NULL,
    is_active    boolean NOT NULL DEFAULT true,
    orden        integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_validacion_procesos PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_procesos_key ON public.validacion_procesos (key);

CREATE TABLE IF NOT EXISTS public.validacion_flujos (
    id                            integer GENERATED BY DEFAULT AS IDENTITY,
    company_id                    integer NOT NULL,
    proceso_id                    integer NOT NULL,
    version                       integer NOT NULL,
    nombre                        character varying(160) NOT NULL,
    estado                        character varying(12) NOT NULL DEFAULT 'BORRADOR',
    plazo_total_horas             integer NOT NULL DEFAULT 24,
    requiere_personas_distintas   boolean NOT NULL DEFAULT true,
    permite_aprobacion_creador    boolean NOT NULL DEFAULT false,
    created_by_user_id            uuid NOT NULL,
    published_by_user_id          uuid NULL,
    created_at                    timestamptz NOT NULL DEFAULT now(),
    updated_at                    timestamptz NULL,
    published_at                  timestamptz NULL,
    retired_at                    timestamptz NULL,
    CONSTRAINT pk_validacion_flujos PRIMARY KEY (id),
    CONSTRAINT ck_validacion_flujos_estado_valido CHECK (estado IN ('BORRADOR','PUBLICADO','RETIRADO')),
    CONSTRAINT ck_validacion_flujos_plazo_positivo CHECK (plazo_total_horas > 0),
    CONSTRAINT fk_validacion_flujos_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_validacion_flujos_validacion_procesos_proceso_id
        FOREIGN KEY (proceso_id) REFERENCES public.validacion_procesos (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_flujos_company_proceso_version
    ON public.validacion_flujos (company_id, proceso_id, version);
CREATE INDEX IF NOT EXISTS ix_validacion_flujos_proceso_id ON public.validacion_flujos (proceso_id);
-- Solo una versión PUBLICADO vigente por empresa/proceso (plan §6.2).
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_flujos_publicado_unico
    ON public.validacion_flujos (company_id, proceso_id)
    WHERE estado = 'PUBLICADO';

CREATE TABLE IF NOT EXISTS public.validacion_flujo_pasos (
    id                       integer GENERATED BY DEFAULT AS IDENTITY,
    flujo_id                 integer NOT NULL,
    orden                    integer NOT NULL,
    nombre                   character varying(120) NOT NULL,
    aprobaciones_requeridas  integer NOT NULL DEFAULT 1,
    descripcion              text NULL,
    CONSTRAINT pk_validacion_flujo_pasos PRIMARY KEY (id),
    CONSTRAINT ck_validacion_flujo_pasos_orden_rango CHECK (orden BETWEEN 1 AND 20),
    CONSTRAINT ck_validacion_flujo_pasos_aprobaciones_positivas CHECK (aprobaciones_requeridas > 0),
    CONSTRAINT fk_validacion_flujo_pasos_validacion_flujos_flujo_id
        FOREIGN KEY (flujo_id) REFERENCES public.validacion_flujos (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_flujo_pasos_flujo_orden
    ON public.validacion_flujo_pasos (flujo_id, orden);

CREATE TABLE IF NOT EXISTS public.validacion_flujo_asignados (
    id                     integer GENERATED BY DEFAULT AS IDENTITY,
    paso_id                integer NOT NULL,
    tipo                   character varying(10) NOT NULL,
    role_id                integer NULL,
    user_id                uuid NULL,
    rol_filtro_origen_id   integer NULL,
    CONSTRAINT pk_validacion_flujo_asignados PRIMARY KEY (id),
    CONSTRAINT ck_validacion_flujo_asignados_tipo_valido CHECK (tipo IN ('ROL','USUARIO')),
    CONSTRAINT ck_validacion_flujo_asignados_tipo_responsable CHECK (
        (tipo = 'ROL' AND role_id IS NOT NULL AND user_id IS NULL) OR
        (tipo = 'USUARIO' AND user_id IS NOT NULL AND role_id IS NULL)
    ),
    CONSTRAINT fk_validacion_flujo_asignados_validacion_flujo_pasos_paso_id
        FOREIGN KEY (paso_id) REFERENCES public.validacion_flujo_pasos (id) ON DELETE CASCADE,
    CONSTRAINT fk_validacion_flujo_asignados_roles_role_id
        FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_validacion_flujo_asignados_paso_id ON public.validacion_flujo_asignados (paso_id);
CREATE INDEX IF NOT EXISTS ix_validacion_flujo_asignados_paso_role ON public.validacion_flujo_asignados (paso_id, role_id);
CREATE INDEX IF NOT EXISTS ix_validacion_flujo_asignados_paso_user ON public.validacion_flujo_asignados (paso_id, user_id);

CREATE TABLE IF NOT EXISTS public.validacion_instancias (
    id                  uuid NOT NULL,
    company_id          integer NOT NULL,
    proceso_id          integer NOT NULL,
    flujo_id            integer NOT NULL,
    recurso_tipo        character varying(60) NOT NULL,
    recurso_id          character varying(64) NOT NULL,
    intento             integer NOT NULL DEFAULT 1,
    estado              character varying(24) NOT NULL DEFAULT 'PENDIENTE_VALIDACION',
    paso_actual_orden   integer NOT NULL,
    paso_retorno_orden  integer NULL,
    created_by_user_id  uuid NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NULL,
    completed_at        timestamptz NULL,
    returned_at         timestamptz NULL,
    cancelled_at        timestamptz NULL,
    motivo_estado       text NULL,
    CONSTRAINT pk_validacion_instancias PRIMARY KEY (id),
    CONSTRAINT ck_validacion_instancias_estado_valido CHECK (
        estado IN ('PENDIENTE_VALIDACION','DEVUELTA_CORRECCION','APROBADA','CANCELADA','ERROR_FINALIZACION')),
    CONSTRAINT ck_validacion_instancias_intento_positivo CHECK (intento > 0),
    CONSTRAINT fk_validacion_instancias_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_validacion_instancias_validacion_procesos_proceso_id
        FOREIGN KEY (proceso_id) REFERENCES public.validacion_procesos (id) ON DELETE RESTRICT,
    CONSTRAINT fk_validacion_instancias_validacion_flujos_flujo_id
        FOREIGN KEY (flujo_id) REFERENCES public.validacion_flujos (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_validacion_instancias_recurso
    ON public.validacion_instancias (company_id, proceso_id, recurso_tipo, recurso_id);
CREATE INDEX IF NOT EXISTS ix_validacion_instancias_company_estado ON public.validacion_instancias (company_id, estado);
CREATE INDEX IF NOT EXISTS ix_validacion_instancias_flujo_id ON public.validacion_instancias (flujo_id);
CREATE INDEX IF NOT EXISTS ix_validacion_instancias_proceso_id ON public.validacion_instancias (proceso_id);
-- Una sola instancia ACTIVA (PENDIENTE_VALIDACION o DEVUELTA_CORRECCION) por recurso (plan §6.5).
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_instancias_activa_unica
    ON public.validacion_instancias (company_id, proceso_id, recurso_tipo, recurso_id)
    WHERE estado IN ('PENDIENTE_VALIDACION','DEVUELTA_CORRECCION');

CREATE TABLE IF NOT EXISTS public.validacion_instancia_pasos (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY,
    instancia_id             uuid NOT NULL,
    paso_definicion_id       integer NOT NULL,
    orden                    integer NOT NULL,
    nombre                   character varying(120) NOT NULL,
    aprobaciones_requeridas  integer NOT NULL DEFAULT 1,
    estado                   character varying(24) NOT NULL DEFAULT 'BLOQUEADA',
    opened_at                timestamptz NULL,
    completed_at             timestamptz NULL,
    CONSTRAINT pk_validacion_instancia_pasos PRIMARY KEY (id),
    CONSTRAINT ck_validacion_instancia_pasos_estado_valido CHECK (
        estado IN ('BLOQUEADA','PENDIENTE','APROBADA','DEVUELTA','ESPERANDO_CORRECCION','CANCELADA')),
    CONSTRAINT fk_validacion_instancia_pasos_validacion_instancias_instancia
        FOREIGN KEY (instancia_id) REFERENCES public.validacion_instancias (id) ON DELETE CASCADE,
    CONSTRAINT fk_validacion_instancia_pasos_validacion_flujo_pasos_paso_def
        FOREIGN KEY (paso_definicion_id) REFERENCES public.validacion_flujo_pasos (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_instancia_pasos_instancia_orden
    ON public.validacion_instancia_pasos (instancia_id, orden);
CREATE INDEX IF NOT EXISTS ix_validacion_instancia_pasos_instancia_estado
    ON public.validacion_instancia_pasos (instancia_id, estado);
CREATE INDEX IF NOT EXISTS ix_validacion_instancia_pasos_paso_definicion_id
    ON public.validacion_instancia_pasos (paso_definicion_id);

CREATE TABLE IF NOT EXISTS public.validacion_acciones (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    instancia_id        uuid NOT NULL,
    instancia_paso_id   bigint NOT NULL,
    accion              character varying(12) NOT NULL,
    user_id             uuid NOT NULL,
    asignado_id         integer NULL,
    comentario          text NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_validacion_acciones PRIMARY KEY (id),
    CONSTRAINT ck_validacion_acciones_accion_valida CHECK (
        accion IN ('APROBAR','DEVOLVER','EDITAR','REENVIAR','ELIMINAR','CANCELAR','OVERRIDE')),
    CONSTRAINT fk_validacion_acciones_validacion_instancias_instancia_id
        FOREIGN KEY (instancia_id) REFERENCES public.validacion_instancias (id) ON DELETE CASCADE,
    CONSTRAINT fk_validacion_acciones_validacion_instancia_pasos_instancia_p
        FOREIGN KEY (instancia_paso_id) REFERENCES public.validacion_instancia_pasos (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_validacion_acciones_instancia_id ON public.validacion_acciones (instancia_id);
CREATE INDEX IF NOT EXISTS ix_validacion_acciones_paso_accion ON public.validacion_acciones (instancia_paso_id, accion);
-- La misma persona no firma dos veces la misma etapa con APROBAR (plan §6.7).
CREATE UNIQUE INDEX IF NOT EXISTS ux_validacion_acciones_aprobar_unica
    ON public.validacion_acciones (instancia_paso_id, user_id)
    WHERE accion = 'APROBAR';

CREATE TABLE IF NOT EXISTS public.validacion_novedades_usuario (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    instancia_id            uuid NOT NULL,
    accion_devolucion_id    bigint NOT NULL,
    company_id              integer NOT NULL,
    destinatario_user_id    uuid NOT NULL,
    generada_por_user_id    uuid NOT NULL,
    estado                  character varying(12) NOT NULL DEFAULT 'ACTIVA',
    motivo                  text NOT NULL,
    contexto_resumen        jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    read_at                 timestamptz NULL,
    resolved_at             timestamptz NULL,
    resolved_by_user_id     uuid NULL,
    resolucion              character varying(24) NULL,
    CONSTRAINT pk_validacion_novedades_usuario PRIMARY KEY (id),
    CONSTRAINT ck_validacion_novedades_estado_valido CHECK (estado IN ('ACTIVA','RESUELTA','CANCELADA')),
    CONSTRAINT ck_validacion_novedades_resolucion_valida CHECK (
        resolucion IS NULL OR resolucion IN ('CORREGIDO_REENVIADO','DEVUELTO_ATRAS','ELIMINADO')),
    CONSTRAINT fk_validacion_novedades_usuario_validacion_instancias_instan
        FOREIGN KEY (instancia_id) REFERENCES public.validacion_instancias (id) ON DELETE CASCADE,
    CONSTRAINT fk_validacion_novedades_usuario_validacion_acciones_accion_d
        FOREIGN KEY (accion_devolucion_id) REFERENCES public.validacion_acciones (id) ON DELETE RESTRICT,
    CONSTRAINT fk_validacion_novedades_usuario_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_validacion_novedades_destinatario_estado
    ON public.validacion_novedades_usuario (company_id, destinatario_user_id, estado);
CREATE INDEX IF NOT EXISTS ix_validacion_novedades_instancia_id ON public.validacion_novedades_usuario (instancia_id);
CREATE INDEX IF NOT EXISTS ix_validacion_novedades_usuario_accion_devolucion_id
    ON public.validacion_novedades_usuario (accion_devolucion_id);
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.validacion_novedades_usuario;
DROP TABLE IF EXISTS public.validacion_acciones;
DROP TABLE IF EXISTS public.validacion_instancia_pasos;
DROP TABLE IF EXISTS public.validacion_instancias;
DROP TABLE IF EXISTS public.validacion_flujo_asignados;
DROP TABLE IF EXISTS public.validacion_flujo_pasos;
DROP TABLE IF EXISTS public.validacion_flujos;
DROP TABLE IF EXISTS public.validacion_procesos;
");
        }
    }
}
