using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Módulos de permisos: <c>permission_modules</c> (catálogo), <c>permission_module_permissions</c>
    /// (clasificación M:N) y <c>company_permission_modules</c> (qué módulos tiene cada empresa).
    /// <para>
    /// Solo crea el schema. La clasificación, los módulos de cada empresa y su efecto sobre
    /// <c>company_permissions</c> los siembra <c>SeedModulosDePermisos</c>, que corre inmediatamente
    /// después. Hasta que ese seed pase, las tablas están vacías y NADA cambia: el runtime sigue
    /// leyendo sólo <c>company_permissions</c>, y una empresa sin filas de módulos no valida el ajuste fino.
    /// </para>
    /// <para>
    /// SQL crudo con <c>IF NOT EXISTS</c> en vez de <c>CreateTable</c>: idempotente (patrón de
    /// <c>AddCompanyPermissions</c>). Plan: <c>fase_de_desarrollo/modulos_permisos_por_empresa_plan.md</c>.
    /// </para>
    /// </summary>
    public partial class AddModulosDePermisos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.permission_modules (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    key         character varying(60)  NOT NULL,
    nombre      character varying(120) NOT NULL,
    descripcion text NULL,
    orden       integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_permission_modules PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_permission_modules_key
    ON public.permission_modules (key);

CREATE TABLE IF NOT EXISTS public.permission_module_permissions (
    module_id     integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT pk_permission_module_permissions PRIMARY KEY (module_id, permission_id),
    CONSTRAINT fk_permission_module_permissions_permission_modules_module_id
        FOREIGN KEY (module_id) REFERENCES public.permission_modules (id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_module_permissions_permissions_permission_id
        FOREIGN KEY (permission_id) REFERENCES public.permissions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_permission_module_permissions_permission_id
    ON public.permission_module_permissions (permission_id);

CREATE TABLE IF NOT EXISTS public.company_permission_modules (
    company_id integer NOT NULL,
    module_id  integer NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_company_permission_modules PRIMARY KEY (company_id, module_id),
    CONSTRAINT fk_company_permission_modules_companies_company_id
        FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_company_permission_modules_permission_modules_module_id
        FOREIGN KEY (module_id) REFERENCES public.permission_modules (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_company_permission_modules_module_id
    ON public.company_permission_modules (module_id);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.company_permission_modules;
DROP TABLE IF EXISTS public.permission_module_permissions;
DROP TABLE IF EXISTS public.permission_modules;
");
        }
    }
}
