using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDbStudioGrantsAndAudit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotente (regla del repo): el deploy aplica esto al arrancar y debe ser
            // seguro re-ejecutar aunque las tablas/índices ya existan.

            // Reconciliación: producción arrastra una versión VIEJA/incompatible de
            // public.dbstudio_audit (columnas table_name / created_at / actor_user_id text,
            // sin success / actor_email / company_id / ip_address / created_at_utc / object_name),
            // creada por una iteración previa de DB Studio. Con CREATE TABLE IF NOT EXISTS esa
            // tabla no se reconstruye y el índice sobre created_at_utc falla, tumbando el arranque.
            // La tabla de auditoría está vacía y sin dependencias (FK/vistas), así que la
            // eliminamos para recrearla con el esquema que exige la entidad DbStudioAudit.
            // El guard (ausencia de created_at_utc, marca inequívoca del esquema nuevo) garantiza
            // que NUNCA se borre una tabla ya correcta: idempotente y seguro de re-ejecutar.
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'dbstudio_audit'
                    )
                    AND NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'dbstudio_audit'
                          AND column_name = 'created_at_utc'
                    )
                    THEN
                        DROP TABLE public.dbstudio_audit CASCADE;
                    END IF;
                END $$;");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.dbstudio_audit (
                    id              bigint GENERATED BY DEFAULT AS IDENTITY,
                    action          varchar(64)  NOT NULL,
                    schema_name     varchar(128) NULL,
                    object_name     varchar(256) NULL,
                    sql_text        text         NOT NULL,
                    result_summary  jsonb        NOT NULL,
                    success         boolean      NOT NULL,
                    actor_user_id   uuid         NULL,
                    actor_email     varchar(256) NULL,
                    company_id      integer      NOT NULL,
                    ip_address      varchar(64)  NULL,
                    created_at_utc  timestamptz  NOT NULL,
                    CONSTRAINT pk_dbstudio_audit PRIMARY KEY (id)
                );");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.dbstudio_object_grant (
                    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
                    user_id             uuid         NOT NULL,
                    company_id          integer      NOT NULL,
                    schema_name         varchar(128) NOT NULL,
                    object_name         varchar(256) NOT NULL,
                    access_level        integer      NOT NULL,
                    granted_by_user_id  uuid         NOT NULL,
                    granted_at_utc      timestamptz  NOT NULL,
                    CONSTRAINT pk_dbstudio_object_grant PRIMARY KEY (id)
                );");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_dbstudio_audit_actor ON public.dbstudio_audit (actor_user_id);");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_dbstudio_audit_created_at ON public.dbstudio_audit (created_at_utc);");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS ux_dbstudio_grant_user_object ON public.dbstudio_object_grant (user_id, company_id, schema_name, object_name);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "dbstudio_audit",
                schema: "public");

            migrationBuilder.DropTable(
                name: "dbstudio_object_grant",
                schema: "public");
        }
    }
}
