using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Santa Reyes — Fase 3: EDADES POR COHORTE + traslado de aves CROSS-ETAPA por empresa.
    /// <list type="number">
    /// <item>
    /// Tabla <c>lote_aves_cohortes</c>: cada grupo de aves recibido por un lote conserva la
    /// <c>fecha_encaset_cohorte</c> de su lote ORIGEN, de modo que un lote puede tener aves propias de
    /// N semanas y aves recibidas de M semanas, cada una contando su propia edad. Se alimenta desde
    /// el traslado de aves del seguimiento diario (misma transacción) y queda ligada al
    /// <c>movimiento_aves_id</c> de auditoría para poder revertirse.
    /// </item>
    /// <item>
    /// Flag tipado <c>companies.permite_traslado_aves_cross_etapa</c> (default <c>false</c> = todas las
    /// empresas actuales siguen bloqueando el traslado entre etapas). Con el flag en <c>true</c> se
    /// habilita EXCLUSIVAMENTE el sentido Levante → Producción (nunca el inverso), que es como Santa
    /// Reyes liquida su levante (~semana 16) contra un lote de producción que ya tiene aves.
    /// </item>
    /// </list>
    /// Enciende el flag SOLO para la empresa <c>Santa Reyes</c> (sembrada por
    /// <c>20260725190000_SeedEmpresaSantaReyes</c>, que corre ANTES que esta — de ahí el timestamp).
    /// Aditiva e <b>idempotente</b> (IF NOT EXISTS + UPDATE con guarda): re-ejecutable sin efectos.
    /// </summary>
    public partial class AddCohortesTrasladoCrossEtapa : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── 1. Flag de empresa ───────────────────────────────────────
            migrationBuilder.Sql(@"
ALTER TABLE public.companies
    ADD COLUMN IF NOT EXISTS permite_traslado_aves_cross_etapa boolean NOT NULL DEFAULT false;
");

            // ── 2. Cohortes de aves por lote ─────────────────────────────
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.lote_aves_cohortes (
    id                     integer GENERATED BY DEFAULT AS IDENTITY,
    lote_id                integer NOT NULL,
    lote_origen_id         integer NULL,
    movimiento_aves_id     integer NULL,
    fecha_ingreso          date NOT NULL,
    fecha_encaset_cohorte  date NOT NULL,
    cantidad_hembras       integer NOT NULL DEFAULT 0,
    cantidad_machos        integer NOT NULL DEFAULT 0,
    observaciones          character varying(300) NULL,
    company_id             integer NOT NULL,
    created_by_user_id     integer NOT NULL,
    created_at             timestamp with time zone NOT NULL,
    updated_by_user_id     integer NULL,
    updated_at             timestamp with time zone NULL,
    deleted_at             timestamp with time zone NULL,
    CONSTRAINT pk_lote_aves_cohortes PRIMARY KEY (id),
    CONSTRAINT fk_lote_aves_cohortes_lote FOREIGN KEY (lote_id)
        REFERENCES public.lotes (lote_id) ON DELETE RESTRICT
);
");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_lote_aves_cohortes_lote        ON public.lote_aves_cohortes (lote_id);
CREATE INDEX IF NOT EXISTS ix_lote_aves_cohortes_company     ON public.lote_aves_cohortes (company_id);
CREATE INDEX IF NOT EXISTS ix_lote_aves_cohortes_lote_origen ON public.lote_aves_cohortes (lote_origen_id);
");

            // ── 3. Santa Reyes es la única empresa con traslado cross-etapa ─
            // Lookup por nombre (nunca por id fijo) + guarda IS DISTINCT FROM → re-ejecutable.
            migrationBuilder.Sql(@"
UPDATE public.companies
   SET permite_traslado_aves_cross_etapa = true
 WHERE name = 'Santa Reyes'
   AND permite_traslado_aves_cross_etapa IS DISTINCT FROM true;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP INDEX IF EXISTS public.ix_lote_aves_cohortes_lote_origen;
DROP INDEX IF EXISTS public.ix_lote_aves_cohortes_company;
DROP INDEX IF EXISTS public.ix_lote_aves_cohortes_lote;
");

            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.lote_aves_cohortes;
");

            migrationBuilder.Sql(@"
ALTER TABLE public.companies
    DROP COLUMN IF EXISTS permite_traslado_aves_cross_etapa;
");
        }
    }
}
