using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Módulo Implementación: cronogramas de entrega de la aplicación por empresa con checklist
    /// de doble check (gestor completa → usuario asignado confirma). Crea
    /// <c>implementacion_planes</c> e <c>implementacion_tareas</c>. Up() en SQL crudo idempotente
    /// (CREATE TABLE/INDEX IF NOT EXISTS + FKs guardadas por pg_constraint) siguiendo la regla del
    /// repo y el patrón de 20260702014925_EnsureSeguimientoDiarioAvesEngordePanamaTable; las
    /// definiciones son 1:1 con el modelo EF (ver Designer/snapshot generados).
    /// </summary>
    public partial class AddImplementacionModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.implementacion_planes (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    pais_id integer NULL,
                    nombre character varying(200) NOT NULL,
                    descripcion character varying(2000) NULL,
                    fecha_inicio date NULL,
                    fecha_fin date NULL,
                    estado character varying(20) NOT NULL DEFAULT 'borrador',
                    company_id integer NOT NULL,
                    created_by_user_id integer NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_by_user_id integer NULL,
                    updated_at timestamp with time zone NULL,
                    deleted_at timestamp with time zone NULL,
                    CONSTRAINT pk_implementacion_planes PRIMARY KEY (id),
                    CONSTRAINT ck_implementacion_plan_estado
                        CHECK (estado IN ('borrador', 'en_progreso', 'completado', 'cancelado'))
                );

                CREATE TABLE IF NOT EXISTS public.implementacion_tareas (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    plan_id integer NOT NULL,
                    categoria character varying(100) NOT NULL,
                    titulo character varying(300) NOT NULL,
                    descripcion character varying(2000) NULL,
                    orden integer NOT NULL DEFAULT 0,
                    fecha_programada date NULL,
                    role_id integer NULL,
                    asignado_user_id uuid NULL,
                    estado character varying(20) NOT NULL DEFAULT 'pendiente',
                    fecha_completada timestamp with time zone NULL,
                    completada_por_user_id uuid NULL,
                    fecha_confirmada timestamp with time zone NULL,
                    confirmada_por_user_id uuid NULL,
                    observaciones character varying(2000) NULL,
                    company_id integer NOT NULL,
                    created_by_user_id integer NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_by_user_id integer NULL,
                    updated_at timestamp with time zone NULL,
                    deleted_at timestamp with time zone NULL,
                    CONSTRAINT pk_implementacion_tareas PRIMARY KEY (id),
                    CONSTRAINT ck_implementacion_tarea_estado
                        CHECK (estado IN ('pendiente', 'completada', 'confirmada'))
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tareas_implementacion_planes_plan_id') THEN
                        ALTER TABLE public.implementacion_tareas
                            ADD CONSTRAINT fk_implementacion_tareas_implementacion_planes_plan_id
                            FOREIGN KEY (plan_id) REFERENCES public.implementacion_planes (id) ON DELETE CASCADE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tareas_roles_role_id') THEN
                        ALTER TABLE public.implementacion_tareas
                            ADD CONSTRAINT fk_implementacion_tareas_roles_role_id
                            FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE RESTRICT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tareas_users_asignado_user_id') THEN
                        ALTER TABLE public.implementacion_tareas
                            ADD CONSTRAINT fk_implementacion_tareas_users_asignado_user_id
                            FOREIGN KEY (asignado_user_id) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tareas_users_completada_por_user_id') THEN
                        ALTER TABLE public.implementacion_tareas
                            ADD CONSTRAINT fk_implementacion_tareas_users_completada_por_user_id
                            FOREIGN KEY (completada_por_user_id) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'fk_implementacion_tareas_users_confirmada_por_user_id') THEN
                        ALTER TABLE public.implementacion_tareas
                            ADD CONSTRAINT fk_implementacion_tareas_users_confirmada_por_user_id
                            FOREIGN KEY (confirmada_por_user_id) REFERENCES public.users (id) ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ix_implementacion_planes_company_pais
                    ON public.implementacion_planes (company_id, pais_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_asignado
                    ON public.implementacion_tareas (asignado_user_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_company
                    ON public.implementacion_tareas (company_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_completada_por_user_id
                    ON public.implementacion_tareas (completada_por_user_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_confirmada_por_user_id
                    ON public.implementacion_tareas (confirmada_por_user_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_plan
                    ON public.implementacion_tareas (plan_id);
                CREATE INDEX IF NOT EXISTS ix_implementacion_tareas_role_id
                    ON public.implementacion_tareas (role_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS public.implementacion_tareas;
                DROP TABLE IF EXISTS public.implementacion_planes;
                """);
        }
    }
}
