using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Plan de vacunación estándar por empresa/línea/raza (W1), del que después se materializa el
    /// cronograma de cada lote.
    /// </summary>
    /// <remarks>
    /// <para>
    /// El <c>Up()</c> se reescribió a SQL <b>idempotente</b> (regla de CLAUDE.md §🗄️): el deploy
    /// aplica las migraciones solo al arrancar, y una que falla a mitad deja el historial
    /// inconsistente. Con <c>IF NOT EXISTS</c> re-correrla es un no-op en vez de un error.
    /// </para>
    /// <para>
    /// <b>Aditiva pura:</b> dos tablas nuevas, ninguna existente se toca. Una empresa sin plantillas
    /// se comporta exactamente como hoy — el cronograma se sigue cargando lote por lote.
    /// </para>
    /// </remarks>
    public partial class AddVacunacionPlanPlantilla : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.vacunacion_plan_plantilla (
    id                  integer GENERATED BY DEFAULT AS IDENTITY,
    pais_id             integer NULL,
    nombre              character varying(200) NOT NULL,
    linea_productiva    character varying(20)  NOT NULL,
    raza                character varying(100) NULL,
    vigente_desde       date NULL,
    activa              boolean NOT NULL DEFAULT TRUE,
    notas               character varying(2000) NULL,
    company_id          integer NOT NULL,
    created_by_user_id  integer NOT NULL,
    created_at          timestamp with time zone NOT NULL,
    updated_by_user_id  integer NULL,
    updated_at          timestamp with time zone NULL,
    deleted_at          timestamp with time zone NULL,
    CONSTRAINT pk_vacunacion_plan_plantilla PRIMARY KEY (id),
    CONSTRAINT ck_vpp_linea_valida CHECK (linea_productiva IN ('Levante', 'Produccion', 'Engorde'))
);");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.vacunacion_plan_plantilla_item (
    id                  integer GENERATED BY DEFAULT AS IDENTITY,
    plantilla_id        integer NOT NULL,
    item_inventario_id  integer NOT NULL,
    unidad_objetivo     character varying(10) NOT NULL,
    valor_objetivo      integer NOT NULL,
    rango_dias_antes    integer NOT NULL DEFAULT 0,
    rango_dias_despues  integer NOT NULL DEFAULT 0,
    orden               integer NOT NULL DEFAULT 0,
    notas               character varying(2000) NULL,
    company_id          integer NOT NULL,
    created_by_user_id  integer NOT NULL,
    created_at          timestamp with time zone NOT NULL,
    updated_by_user_id  integer NULL,
    updated_at          timestamp with time zone NULL,
    deleted_at          timestamp with time zone NULL,
    CONSTRAINT pk_vacunacion_plan_plantilla_item PRIMARY KEY (id),
    -- 'Fecha' no entra: una fecha fija no se puede plantillar, seria la misma para lotes
    -- encasetados en meses distintos. Las fechas fijas siguen siendo items manuales del lote.
    CONSTRAINT ck_vppi_unidad_valida CHECK (unidad_objetivo IN ('Semana', 'Dia')),
    CONSTRAINT ck_vppi_valor_nonneg  CHECK (valor_objetivo >= 0),
    CONSTRAINT ck_vppi_rango_nonneg  CHECK (rango_dias_antes >= 0 AND rango_dias_despues >= 0),
    CONSTRAINT fk_vacunacion_plan_plantilla_item_vacunacion_plan_plantilla_pl
        FOREIGN KEY (plantilla_id) REFERENCES public.vacunacion_plan_plantilla (id) ON DELETE CASCADE,
    CONSTRAINT fk_vacunacion_plan_plantilla_item_item_inventario_item_inventa
        FOREIGN KEY (item_inventario_id) REFERENCES public.item_inventario_ecuador (id) ON DELETE RESTRICT
);");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_vacunacion_plan_plantilla_company_linea
    ON public.vacunacion_plan_plantilla (company_id, linea_productiva);");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_vacunacion_plan_plantilla_item_plantilla
    ON public.vacunacion_plan_plantilla_item (plantilla_id);");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_vacunacion_plan_plantilla_item_item_inventario_id
    ON public.vacunacion_plan_plantilla_item (item_inventario_id);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.vacunacion_plan_plantilla_item;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.vacunacion_plan_plantilla;");
        }
    }
}
