using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    /// <summary>
    /// Alcance granular por usuario-granja: además de asignar la granja (user_farms), un usuario
    /// puede quedar restringido DENTRO de ella a ciertos núcleos/galpones/lotes.
    ///
    ///  - user_farms.restrict_locations (bool, default FALSE): false = acceso global a la granja
    ///    (comportamiento clásico, cero cambio para todo usuario existente); true = solo ve la unión
    ///    de sus grants en user_farm_scopes (con cero grants no ve nada: fail-closed).
    ///  - user_farm_scopes: una fila = un grant en exactamente UN nivel (nucleo_id | galpon_id |
    ///    lote_id, CHECK un_nivel). Grant de núcleo cubre sus galpones y lotes; de galpón, sus lotes;
    ///    de lote (tabla lotes), ese lote. Módulos con tabla de lote propia (engorde/postura) se
    ///    gobiernan por los niveles núcleo/galpón.
    ///  - FKs ON DELETE CASCADE a user_farms, nucleos (compuesta con granja), galpones y lotes:
    ///    al eliminar la asignación o el lugar (incluido el copy+DELETE de fn_rekey_nucleo) el grant
    ///    cae y el usuario queda MÁS restringido (fail-closed) hasta re-asignar. Por eso esta tabla
    ///    NO se agrega al inventario de fn_mover_ubicacion.sql: re-apuntar un grant a otra granja
    ///    violaría la FK a user_farms (el usuario puede no tener la granja destino asignada);
    ///    además el resolver valida cada grant contra el catálogo vigente de la granja, de modo que
    ///    una fila obsoleta jamás otorga acceso.
    /// </summary>
    public partial class UserFarmLocationScope : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE public.user_farms ADD COLUMN IF NOT EXISTS restrict_locations boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.user_farm_scopes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    farm_id integer NOT NULL,
    nucleo_id character varying(64) NULL,
    galpon_id character varying(64) NULL,
    lote_id integer NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id uuid NOT NULL,
    CONSTRAINT pk_user_farm_scopes PRIMARY KEY (id),
    CONSTRAINT ck_user_farm_scopes_un_nivel CHECK (
        (CASE WHEN nucleo_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN galpon_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN lote_id  IS NOT NULL THEN 1 ELSE 0 END) = 1),
    CONSTRAINT fk_user_farm_scopes_user_farms FOREIGN KEY (user_id, farm_id)
        REFERENCES public.user_farms (user_id, farm_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_farm_scopes_nucleos FOREIGN KEY (nucleo_id, farm_id)
        REFERENCES public.nucleos (nucleo_id, granja_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_farm_scopes_galpones FOREIGN KEY (galpon_id)
        REFERENCES public.galpones (galpon_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_farm_scopes_lotes FOREIGN KEY (lote_id)
        REFERENCES public.lotes (lote_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_user_farm_scopes_galpon_id        ON public.user_farm_scopes (galpon_id);
CREATE INDEX IF NOT EXISTS ix_user_farm_scopes_lote_id          ON public.user_farm_scopes (lote_id);
CREATE INDEX IF NOT EXISTS ix_user_farm_scopes_nucleo_id_farm_id ON public.user_farm_scopes (nucleo_id, farm_id);
CREATE INDEX IF NOT EXISTS ix_user_farm_scopes_user_farm        ON public.user_farm_scopes (user_id, farm_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_farm_scopes_nucleo ON public.user_farm_scopes (user_id, farm_id, nucleo_id) WHERE nucleo_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_farm_scopes_galpon ON public.user_farm_scopes (user_id, farm_id, galpon_id) WHERE galpon_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_farm_scopes_lote   ON public.user_farm_scopes (user_id, farm_id, lote_id)  WHERE lote_id IS NOT NULL;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.user_farm_scopes;
ALTER TABLE public.user_farms DROP COLUMN IF EXISTS restrict_locations;
");
        }
    }
}
