-- =============================================================================
-- ARCHIVO RETIRADO — la definicion de la vista vive ahora en:
--     backend/sql/vw_seguimiento_pollo_engorde.sql
-- =============================================================================
-- Que pasaba: este archivo definia `vw_seguimiento_pollo_engorde_unificado`, pero la vista que
-- Power BI consume se llama `vw_seguimiento_pollo_engorde` y tiene 67 columnas. A esta definicion
-- le faltaban 14 que la desplegada SI tiene (tipo_fila, uniformidad_*, cv_*, consumo_agua_ph/orp/
-- temperatura, ciclo, historico_consumo_alimento, despacho_peso_*, created_by_user_id) mas
-- consumo_kg_mixto / consumo_es_mixto. Aplicarlo BORRABA esas columnas y rompia los tableros:
-- dos archivos describiendo "la misma" vista con contenidos distintos es justo la trampa que hay
-- que evitar, asi que queda uno solo y es fiel a lo desplegado.
--
-- El SQL completo que estaba aca sigue en el historial de git:
--     git show 2f2a00a:backend/sql/seguimiento_pollo_engorde_tabla_unificada_vista.sql
-- Recuperalo desde ahi si alguna vez hace falta reconstruir `..._unificado` en algun ambiente
-- (en local NO existe esa vista; la migracion 20260812021716 la contempla por si acaso).
--
-- La consulta ad-hoc por lote, que no crea nada, sigue en:
--     backend/sql/seguimiento_pollo_engorde_tabla_unificada.sql
-- =============================================================================
