// src/ZooSanMarino.Application/DTOs/ProduccionAvicolaRawDto.cs
namespace ZooSanMarino.Application.DTOs;

public record ProduccionAvicolaRawDto(
    int Id,
    int CompanyId,
    string? CodigoGuiaGenetica,
    string? AnioGuia,
    string? Raza,
    string? Edad,
    string? MortSemH,
    string? RetiroAcH,
    string? MortSemM,
    string? RetiroAcM,
    string? Hembras,
    string? Machos,
    string? ConsAcH,
    string? ConsAcM,
    string? GrAveDiaH,
    string? GrAveDiaM,
    string? PesoH,
    string? PesoM,
    string? Uniformidad,
    string? HTotalAa,
    string? ProdPorcentaje,
    string? HIncAa,
    string? AprovSem,
    string? PesoHuevo,
    string? MasaHuevo,
    string? GrasaPorcentaje,
    string? NacimPorcentaje,
    string? PollitoAa,
    string? AlimH,
    string? KcalAveDiaH,
    string? KcalAveDiaM,
    string? KcalH,
    string? ProtH,
    string? AlimM,
    string? KcalM,
    string? ProtM,
    string? KcalSemH,
    string? ProtHSem,
    string? KcalSemM,
    string? ProtSemM,
    string? AprovAc,
    string? GrHuevoT,
    string? GrHuevoInc,
    string? GrPollito,
    string? Valor1000,
    string? Valor150,
    string? Apareo,
    string? PesoMh,
    DateTime CreatedAt,
    DateTime? UpdatedAt
);

public record CreateProduccionAvicolaRawDto(
    string? CodigoGuiaGenetica,
    string? AnioGuia,
    string? Raza,
    string? Edad,
    string? MortSemH,
    string? RetiroAcH,
    string? MortSemM,
    string? RetiroAcM,
    string? Hembras,
    string? Machos,
    string? ConsAcH,
    string? ConsAcM,
    string? GrAveDiaH,
    string? GrAveDiaM,
    string? PesoH,
    string? PesoM,
    string? Uniformidad,
    string? HTotalAa,
    string? ProdPorcentaje,
    string? HIncAa,
    string? AprovSem,
    string? PesoHuevo,
    string? MasaHuevo,
    string? GrasaPorcentaje,
    string? NacimPorcentaje,
    string? PollitoAa,
    string? AlimH,
    string? KcalAveDiaH,
    string? KcalAveDiaM,
    string? KcalH,
    string? ProtH,
    string? AlimM,
    string? KcalM,
    string? ProtM,
    string? KcalSemH,
    string? ProtHSem,
    string? KcalSemM,
    string? ProtSemM,
    string? AprovAc,
    string? GrHuevoT,
    string? GrHuevoInc,
    string? GrPollito,
    string? Valor1000,
    string? Valor150,
    string? Apareo,
    string? PesoMh
);

public record UpdateProduccionAvicolaRawDto(
    int Id,
    string? CodigoGuiaGenetica,
    string? AnioGuia,
    string? Raza,
    string? Edad,
    string? MortSemH,
    string? RetiroAcH,
    string? MortSemM,
    string? RetiroAcM,
    string? Hembras,
    string? Machos,
    string? ConsAcH,
    string? ConsAcM,
    string? GrAveDiaH,
    string? GrAveDiaM,
    string? PesoH,
    string? PesoM,
    string? Uniformidad,
    string? HTotalAa,
    string? ProdPorcentaje,
    string? HIncAa,
    string? AprovSem,
    string? PesoHuevo,
    string? MasaHuevo,
    string? GrasaPorcentaje,
    string? NacimPorcentaje,
    string? PollitoAa,
    string? AlimH,
    string? KcalAveDiaH,
    string? KcalAveDiaM,
    string? KcalH,
    string? ProtH,
    string? AlimM,
    string? KcalM,
    string? ProtM,
    string? KcalSemH,
    string? ProtHSem,
    string? KcalSemM,
    string? ProtSemM,
    string? AprovAc,
    string? GrHuevoT,
    string? GrHuevoInc,
    string? GrPollito,
    string? Valor1000,
    string? Valor150,
    string? Apareo,
    string? PesoMh
);

public record ProduccionAvicolaRawSearchRequest(
    string? AnioGuia,
    string? Raza,
    string? Edad,
    int? CompanyId,
    int Page = 1,
    int PageSize = 10,
    string? SortBy = null,
    bool SortDesc = false
);
