namespace ZooSanMarino.Application.DTOs.LoteAveEngorde;

using FarmLiteDto = ZooSanMarino.Application.DTOs.Farms.FarmLiteDto;
using NucleoLiteDto = ZooSanMarino.Application.DTOs.Shared.NucleoLiteDto;
using GalponLiteDto = ZooSanMarino.Application.DTOs.Shared.GalponLiteDto;

public sealed record LoteAveEngordeDetailDto(
    int LoteAveEngordeId,
    string LoteNombre,
    int GranjaId,
    string? NucleoId,
    string? GalponId,
    string? Regional,
    DateTime? FechaEncaset,
    DateTime? FechaAlistamiento,
    int? HembrasL,
    int? MachosL,
    double? PesoInicialH,
    double? PesoInicialM,
    double? UnifH,
    double? UnifM,
    int? MortCajaH,
    int? MortCajaM,
    string? Raza,
    int? AnoTablaGenetica,
    string? Linea,
    string? TipoLinea,
    string? CodigoGuiaGenetica,
    int? LineaGeneticaId,
    string? Tecnico,
    int? Mixtas,
    double? PesoMixto,
    int? AvesEncasetadas,
    int? EdadInicial,
    string? LoteErp,
    string? EstadoTraslado,
    string? EstadoOperativoLote,
    DateTime? LiquidadoAt,
    string? LiquidadoPorUserId,
    DateTime? ReabiertoAt,
    string? ReabiertoPorUserId,
    string? MotivoReapertura,
    // Mermas (R1) y sobrante de aves (R2)
    int? MermaUnidades,
    decimal? MermaKilos,
    DateTime? MermaRegistradaAt,
    string? MermaRegistradaPorUserId,
    int AvesSobrante,
    int? PaisId,
    string? PaisNombre,
    string? EmpresaNombre,
    int CompanyId,
    int CreatedByUserId,
    DateTime CreatedAt,
    int? UpdatedByUserId,
    DateTime? UpdatedAt,
    FarmLiteDto Farm,
    NucleoLiteDto? Nucleo,
    GalponLiteDto? Galpon,
    // Lote base global (opcional): agrupador para reportes por granja
    int? LoteBaseEngordeId = null,
    string? LoteBaseNombre = null
);
